type Booking {
  id: UUID!
  user_id: UUID!
  package_id: UUID!
  total_price: String!
  status: String!
  booking_date: Time!
  travel_start_date: String!
  travel_end_date: String!
  created_at: Time!
  updated_at: Time!

  user: User
  package: Package
}

extend type Query {
  booking(id: UUID!): Booking
  bookings: [Booking!]!
}

extend type Mutation {
  createBooking(user_id:UUID! package_id:UUID! total_price:String! status:String! travel_start_date:String! travel_end_date:String!):Booking!
  updateBooking(id:UUID! user_id:UUID package_id:UUID total_price:String status:String travel_start_date:String travel_end_date:String):Booking!
  deleteBooking(id:UUID!):Booking!
}