package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/internal/db"
	"strconv"
	"time"
)

// ID is the resolver for the id field.
func (r *bookingResolver) ID(ctx context.Context, obj *db.Booking) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// UserID is the resolver for the user_id field.
func (r *bookingResolver) UserID(ctx context.Context, obj *db.Booking) (string, error) {
	return fmt.Sprintf("%d", obj.UserID), nil
}

// PackageID is the resolver for the package_id field.
func (r *bookingResolver) PackageID(ctx context.Context, obj *db.Booking) (string, error) {
	return fmt.Sprintf("%d", obj.PackageID), nil
}

// TravelStartDate is the resolver for the travel_start_date field.
func (r *bookingResolver) TravelStartDate(ctx context.Context, obj *db.Booking) (string, error) {
	// DATE in DB → String in GraphQL schema
	return obj.TravelStartDate.Format("2006-01-02"), nil
}

// TravelEndDate is the resolver for the travel_end_date field.
func (r *bookingResolver) TravelEndDate(ctx context.Context, obj *db.Booking) (string, error) {
	return obj.TravelEndDate.Format("2006-01-02"), nil
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, userID string, packageID string, totalPrice string, status string, travelStartDate string, travelEndDate string) (*db.Booking, error) {
	if userID == "" || packageID == "" || totalPrice == "" || status == "" || travelStartDate == "" || travelEndDate == "" {
		return nil, errors.New("user_id, package_id, total_price, status, travel_start_date and travel_end_date are required")
	}

	uID, err := strconv.Atoi(userID)
	if err != nil {
		return nil, errors.New("invalid user_id")
	}

	pID, err := strconv.Atoi(packageID)
	if err != nil {
		return nil, errors.New("invalid package_id")
	}

	// parse dates (YYYY-MM-DD)
	startDate, err := time.Parse("2006-01-02", travelStartDate)
	if err != nil {
		return nil, errors.New("invalid travel_start_date, expected YYYY-MM-DD")
	}

	endDate, err := time.Parse("2006-01-02", travelEndDate)
	if err != nil {
		return nil, errors.New("invalid travel_end_date, expected YYYY-MM-DD")
	}

	booking, err := database.Queries.CreateBooking(ctx, db.CreateBookingParams{
		UserID:          int32(uID),
		PackageID:       int32(pID),
		TotalPrice:      totalPrice,
		Status:          status,
		TravelStartDate: startDate,
		TravelEndDate:   endDate,
	})
	if err != nil {
		return nil, err
	}

	return &booking, nil
}

// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, id string, userID *string, packageID *string, totalPrice *string, status *string, travelStartDate *string, travelEndDate *string) (*db.Booking, error) {
	bID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid booking id")
	}

	existing, err := database.Queries.GetBooking(ctx, int32(bID))
	if err == sql.ErrNoRows {
		return nil, errors.New("booking not found")
	}
	if err != nil {
		return nil, err
	}

	newUserID := existing.UserID
	if userID != nil {
		uid, err := strconv.Atoi(*userID)
		if err != nil {
			return nil, errors.New("invalid user_id")
		}
		newUserID = int32(uid)
	}

	newPackageID := existing.PackageID
	if packageID != nil {
		pid, err := strconv.Atoi(*packageID)
		if err != nil {
			return nil, errors.New("invalid package_id")
		}
		newPackageID = int32(pid)
	}

	newTotalPrice := existing.TotalPrice
	if totalPrice != nil {
		newTotalPrice = *totalPrice
	}

	newStatus := existing.Status
	if status != nil {
		newStatus = *status
	}

	newStartDate := existing.TravelStartDate
	if travelStartDate != nil {
		d, err := time.Parse("2006-01-02", *travelStartDate)
		if err != nil {
			return nil, errors.New("invalid travel_start_date, expected YYYY-MM-DD")
		}
		newStartDate = d
	}

	newEndDate := existing.TravelEndDate
	if travelEndDate != nil {
		d, err := time.Parse("2006-01-02", *travelEndDate)
		if err != nil {
			return nil, errors.New("invalid travel_end_date, expected YYYY-MM-DD")
		}
		newEndDate = d
	}

	booking, err := database.Queries.UpdateBooking(ctx, db.UpdateBookingParams{
		ID:              int32(bID),
		UserID:          newUserID,
		PackageID:       newPackageID,
		TotalPrice:      newTotalPrice,
		Status:          newStatus,
		TravelStartDate: newStartDate,
		TravelEndDate:   newEndDate,
	})
	if err != nil {
		return nil, err
	}

	return &booking, nil
}

// DeleteBooking is the resolver for the deleteBooking field.
func (r *mutationResolver) DeleteBooking(ctx context.Context, id string) (*db.Booking, error) {
	bID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid booking id")
	}

	booking, err := database.Queries.DeleteBooking(ctx, int32(bID))
	if err == sql.ErrNoRows {
		return nil, errors.New("booking not found")
	}
	if err != nil {
		return nil, err
	}

	return &booking, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*db.Booking, error) {
	bID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid booking id")
	}

	booking, err := database.Queries.GetBooking(ctx, int32(bID))
	if err == sql.ErrNoRows {
		return nil, errors.New("booking not found")
	}
	if err != nil {
		return nil, err
	}

	return &booking, nil
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context) ([]*db.Booking, error) {
	bookingsDB, err := database.Queries.ListBookings(ctx)
	if err != nil {
		return nil, err
	}

	bookings := make([]*db.Booking, 0, len(bookingsDB))
	for i := range bookingsDB {
		b := bookingsDB[i]
		bookings = append(bookings, &b)
	}

	return bookings, nil
}

// Booking returns generated.BookingResolver implementation.
func (r *Resolver) Booking() generated.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
