package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/internal/db"
	"strconv"
)

// Description is the resolver for the description field.
func (r *categoryResolver) Description(ctx context.Context, obj *db.Category) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	desc := obj.Description.String
	return &desc, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, categoryName string, description *string) (*db.Category, error) {
	if categoryName == "" {
		return nil, errors.New("category_name is required")
	}

	var desc sql.NullString
	if description != nil {
		desc = sql.NullString{String: *description, Valid: true}
	}

	cat, err := database.Queries.CreateCategory(ctx, db.CreateCategoryParams{
		CategoryName: categoryName,
		Description:  desc,
	})
	if err != nil {
		return nil, err
	}

	return &cat, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, categoryName *string, description *string) (*db.Category, error) {
	catID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid category id")
	}

	// Fetch existing category for defaults
	existing, err := database.Queries.GetCategory(ctx, int32(catID))
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	// Resolve new values
	nameVal := existing.CategoryName
	if categoryName != nil {
		nameVal = *categoryName
	}

	descVal := existing.Description
	if description != nil {
		descVal = sql.NullString{String: *description, Valid: true}
	}

	cat, err := database.Queries.UpdateCategory(ctx, db.UpdateCategoryParams{
		ID:           int32(catID),
		CategoryName: nameVal,
		Description:  descVal,
	})
	if err != nil {
		return nil, err
	}

	return &cat, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (*db.Category, error) {
	catID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid category id")
	}

	cat, err := database.Queries.DeleteCategory(ctx, int32(catID))
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	return &cat, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*db.Category, error) {
	categoryID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid category ID")
	}

	categoryDB, err := database.Queries.GetCategory(ctx, int32(categoryID))
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	return &categoryDB, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*db.Category, error) {
	categoriesDB, err := database.Queries.ListCategories(ctx)
	if err != nil {
		return nil, err
	}

	// Convert []Category to []*Category
	categories := make([]*db.Category, len(categoriesDB))
	for i := range categoriesDB {
		categories[i] = &categoriesDB[i]
	}

	return categories, nil
}
