package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	stdErrors "errors"
	"fmt"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/db"

	dbtime "graphql/internal/dbTime"
	appErr "graphql/internal/errors"

	"github.com/google/uuid"
)

// Description is the resolver for the description field.
func (r *categoryResolver) Description(ctx context.Context, obj *db.Category) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	desc := obj.Description.String
	return &desc, nil
}

// Images is the resolver for the images field.
func (r *categoryResolver) Images(ctx context.Context, obj *db.Category) ([]*db.CategoryImage, error) {
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	imgs, err := database.Queries.ListCategoryImagesByCategory(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.CategoryImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// AltText is the resolver for the alt_text field.
func (r *categoryImageResolver) AltText(ctx context.Context, obj *db.CategoryImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, categoryName string, description *string, images []*models.CategoryImageInput) (*db.Category, error) {
	if categoryName == "" {
		return nil, appErr.InvalidInput()
	}

	var desc sql.NullString
	if description != nil {
		desc = sql.NullString{String: *description, Valid: true}
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// START TRANSACTION
	tx, err := database.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback() // auto rollback on error

	qtx := database.Queries.WithTx(tx)

	// Create category
	cat, err := qtx.CreateCategory(ctx, db.CreateCategoryParams{
		CategoryName: categoryName,
		Description:  desc,
	})
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	// Insert images
	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		var alt sql.NullString
		if img.AltText != nil {
			alt = sql.NullString{String: *img.AltText, Valid: true}
		}

		if _, err := qtx.CreateCategoryImage(ctx, db.CreateCategoryImageParams{
			CategoryID: cat.ID,
			FileUrl:    img.FileURL,
			AltText:    alt,
		}); err != nil {
			return nil, appErr.Internal(err)
		}
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return &cat, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, categoryName *string, description *string, images []*models.CategoryImageInput) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, appErr.InvalidInput()
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// START TRANSACTION
	tx, err := database.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("start tx failed: %w", err)
	}
	defer tx.Rollback()

	qtx := database.Queries.WithTx(tx)

	// Existing row
	existing, err := qtx.GetCategory(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	newName := existing.CategoryName
	if categoryName != nil {
		newName = *categoryName
	}

	newDesc := existing.Description
	if description != nil {
		newDesc = sql.NullString{String: *description, Valid: true}
	}

	// Update category
	cat, err := qtx.UpdateCategory(ctx, db.UpdateCategoryParams{
		ID:          id,
		Column2:     newName,
		Description: newDesc,
	})
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	// Replace images atomically
	if images != nil {
		if err := qtx.DeleteCategoryImagesByCategory(ctx, cat.ID); err != nil {
			return nil, appErr.Internal(err)
		}

		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			var alt sql.NullString
			if img.AltText != nil {
				alt = sql.NullString{String: *img.AltText, Valid: true}
			}

			if _, err := qtx.CreateCategoryImage(ctx, db.CreateCategoryImageParams{
				CategoryID: cat.ID,
				FileUrl:    img.FileURL,
				AltText:    alt,
			}); err != nil {
				return nil, fmt.Errorf("create category image failed: %w", err)
			}
		}
	}

	// COMMIT

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit failed: %w", err)
	}

	return &cat, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid category id")
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	cat, err := database.Queries.DeleteCategory(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	return &cat, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, appErr.InvalidInput()
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	categoryDB, err := database.Queries.GetCategory(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	return &categoryDB, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, limit *int, offset *int) ([]*db.Category, error) {
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()

	var l int32 = 20
	var o int32 = 0

	if limit != nil && *limit > 0 {
		l = int32(*limit)
	}
	if offset != nil && *offset >= 0 {
		o = int32(*offset)
	}

	categoriesDB, err := database.Queries.ListCategories(
		ctx,
		db.ListCategoriesParams{
			Limit:  l,
			Offset: o,
		},
	)
	if err != nil {
		return nil, err
	}

	categories := make([]*db.Category, len(categoriesDB))
	for i := range categoriesDB {
		categories[i] = &categoriesDB[i]
	}

	return categories, nil
}

// CategoryImage is the resolver for the categoryImage field.
func (r *queryResolver) CategoryImage(ctx context.Context, id uuid.UUID) (*db.CategoryImage, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid image id")
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	img, err := database.Queries.GetCategoryImageByID(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	return &img, nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// CategoryImage returns generated.CategoryImageResolver implementation.
func (r *Resolver) CategoryImage() generated.CategoryImageResolver { return &categoryImageResolver{r} }

type categoryResolver struct{ *Resolver }
type categoryImageResolver struct{ *Resolver }
