type Category {
  id: UUID!
  category_name: String!
  description: String
  created_at: Time!
  updated_at: Time!
  images: [CategoryImage!]!
}

type CategoryImage {
  id: UUID!
  category_id: UUID!
  file_url: String!
  alt_text: String
  created_at: Time!
  updated_at: Time!
}

input CategoryImageInput {
  file_url: String!
  alt_text: String
}

extend type Query {
  category(id: UUID!): Category
categories(
  limit: Int = 20
  offset: Int = 0
): [Category!]!

  categoryImage(id: UUID!): CategoryImage!
}

extend type Mutation {
  createCategory(
    category_name: String!
    description: String
    images: [CategoryImageInput!]
  ): Category!

  updateCategory(
    id: UUID!
    category_name: String
    description: String
    images: [CategoryImageInput!]
  ): Category!

  deleteCategory(id: UUID!): Category!
}
