package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/db"

	"github.com/google/uuid"
)

// Description is the resolver for the description field.
func (r *categoryResolver) Description(ctx context.Context, obj *db.Category) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	desc := obj.Description.String
	return &desc, nil
}

// Images is the resolver for the images field.
func (r *categoryResolver) Images(ctx context.Context, obj *db.Category) ([]*db.CategoryImage, error) {
	imgs, err := database.Queries.ListCategoryImagesByCategory(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.CategoryImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// AltText is the resolver for the alt_text field.
func (r *categoryImageResolver) AltText(ctx context.Context, obj *db.CategoryImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, categoryName string, description *string, images []*models.CategoryImageInput) (*db.Category, error) {
	if categoryName == "" {
		return nil, errors.New("category_name is required")
	}

	var desc sql.NullString
	if description != nil {
		desc = sql.NullString{String: *description, Valid: true}
	}

	// 1) Category create
	cat, err := database.Queries.CreateCategory(ctx, db.CreateCategoryParams{
		CategoryName: categoryName,
		Description:  desc,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images insert (EXACT SAME AS PACKAGE)
	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		var alt sql.NullString
		if img.AltText != nil {
			alt = sql.NullString{String: *img.AltText, Valid: true}
		}

		_, err := database.Queries.CreateCategoryImage(ctx, db.CreateCategoryImageParams{
			CategoryID: cat.ID,
			FileUrl:    img.FileURL,
			AltText:    alt,
		})
		if err != nil {
			return nil, err
		}
	}

	return &cat, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, categoryName *string, description *string, images []*models.CategoryImageInput) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid category id")
	}

	// existing row for defaults
	existing, err := database.Queries.GetCategory(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	// Resolve new values
	newName := existing.CategoryName
	if categoryName != nil {
		newName = *categoryName
	}

	newDesc := existing.Description
	if description != nil {
		newDesc = sql.NullString{String: *description, Valid: true}
	}

	// 1) Category update
	cat, err := database.Queries.UpdateCategory(ctx, db.UpdateCategoryParams{
		ID:           id,
		CategoryName: newName,
		Description:  newDesc,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images replace if provided (EXACT SAME AS PACKAGE)
	if images != nil {
		// Delete old images
		if err := database.Queries.DeleteCategoryImagesByCategory(ctx, cat.ID); err != nil {
			return nil, err
		}

		// Insert new images
		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			var alt sql.NullString
			if img.AltText != nil {
				alt = sql.NullString{String: *img.AltText, Valid: true}
			}

			_, err := database.Queries.CreateCategoryImage(ctx, db.CreateCategoryImageParams{
				CategoryID: cat.ID,
				FileUrl:    img.FileURL,
				AltText:    alt,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	return &cat, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid category id")
	}

	cat, err := database.Queries.DeleteCategory(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	return &cat, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*db.Category, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid category ID")
	}

	categoryDB, err := database.Queries.GetCategory(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("category not found")
	}
	if err != nil {
		return nil, err
	}

	return &categoryDB, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*db.Category, error) {
	categoriesDB, err := database.Queries.ListCategories(ctx)
	if err != nil {
		return nil, err
	}

	categories := make([]*db.Category, len(categoriesDB))
	for i := range categoriesDB {
		categories[i] = &categoriesDB[i]
	}
	return categories, nil
}

// CategoryImage is the resolver for the categoryImage field.
func (r *queryResolver) CategoryImage(ctx context.Context, id uuid.UUID) (*db.CategoryImage, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid image id")
	}

	img, err := database.Queries.GetCategoryImageByID(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("image not found")
	}
	if err != nil {
		return nil, err
	}

	return &img, nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// CategoryImage returns generated.CategoryImageResolver implementation.
func (r *Resolver) CategoryImage() generated.CategoryImageResolver { return &categoryImageResolver{r} }

type categoryResolver struct{ *Resolver }
type categoryImageResolver struct{ *Resolver }
