package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/internal/db"
	"strconv"
)

// StateID is the resolver for the stateId field.
func (r *cityResolver) StateID(ctx context.Context, obj *db.City) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateCity is the resolver for the createCity field.
func (r *mutationResolver) CreateCity(ctx context.Context, stateID string, name string) (*db.City, error) {
	if name == "" {
		return nil, errors.New("city name is required")
	}

	sID, err := strconv.Atoi(stateID)
	if err != nil {
		return nil, errors.New("invalid state id")
	}

	city, err := database.Queries.CreateCity(ctx, db.CreateCityParams{
		StateID: int32(sID),
		Name:    name,
	})
	if err != nil {
		return nil, err
	}

	return &city, nil
}

// UpdateCity is the resolver for the updateCity field.
func (r *mutationResolver) UpdateCity(ctx context.Context, id string, stateID *string, name *string) (*db.City, error) {
	// Convert id string to int32
	cityID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid city id")
	}

	// Prepare parameters
	var sID int32
	if stateID != nil {
		sidInt, err := strconv.Atoi(*stateID)
		if err != nil {
			return nil, errors.New("invalid state id")
		}
		sID = int32(sidInt)
	}

	// Fetch existing city
	existingCity, err := database.Queries.GetCity(ctx, int32(cityID))
	if err != nil {
		return nil, err
	}

	// Update fields if provided
	updatedCity, err := database.Queries.UpdateCity(ctx, db.UpdateCityParams{
		ID: int32(cityID),
		StateID: func() int32 {
			if stateID != nil {
				return sID
			}
			return existingCity.StateID
		}(),
		Name: func() string {
			if name != nil {
				return *name
			}
			return existingCity.Name
		}(),
	})
	if err != nil {
		return nil, err
	}

	return &updatedCity, nil
}

// DeleteCity is the resolver for the deleteCity field.
func (r *mutationResolver) DeleteCity(ctx context.Context, id string) (*db.City, error) {
	cityID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid city id")
	}

	// Call SQL query to delete city
	city, err := database.Queries.DeleteCity(ctx, int32(cityID))
	if err != nil {
		return nil, err
	}

	return &city, nil
}

// City is the resolver for the city field.
func (r *queryResolver) City(ctx context.Context, id string) (*db.City, error) {
	cityID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid city id")
	}

	city, err := database.Queries.GetCity(ctx, int32(cityID))
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.New("city not found")
		}
		return nil, err
	}

	return &city, nil
}

// Cities is the resolver for the cities field.
func (r *queryResolver) Cities(ctx context.Context) ([]*db.City, error) {
	cities, err := database.Queries.ListCities(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*db.City, 0, len(cities))
	for _, city := range cities {
		c := city // avoid pointer reuse bug
		result = append(result, &c)
	}

	return result, nil
}

// CitiesByState is the resolver for the citiesByState field.
func (r *queryResolver) CitiesByState(ctx context.Context, stateID string) ([]*db.City, error) {
	sID, err := strconv.Atoi(stateID)
	if err != nil {
		return nil, errors.New("invalid state id")
	}

	cities, err := database.Queries.ListCitiesByState(ctx, int32(sID))
	if err != nil {
		return nil, err
	}

	result := make([]*db.City, 0, len(cities))
	for _, city := range cities {
		c := city // avoid pointer reuse bug
		result = append(result, &c)
	}

	return result, nil
}
