package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/internal/db"

	"github.com/google/uuid"
)

// CreateCity is the resolver for the createCity field.
func (r *mutationResolver) CreateCity(ctx context.Context, stateID uuid.UUID, name string) (*db.City, error) {
	if stateID == uuid.Nil {
		return nil, errors.New("invalid state id")
	}
	if name == "" {
		return nil, errors.New("city name is required")
	}

	city, err := database.Queries.CreateCity(ctx, db.CreateCityParams{
		StateID: stateID,
		Name:    name,
	})
	if err != nil {
		return nil, err
	}

	return &city, nil
}

// UpdateCity is the resolver for the updateCity field.
func (r *mutationResolver) UpdateCity(ctx context.Context, id uuid.UUID, stateID *uuid.UUID, name *string) (*db.City, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid city id")
	}

	existingCity, err := database.Queries.GetCity(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("city not found")
	}
	if err != nil {
		return nil, err
	}

	newStateID := existingCity.StateID
	if stateID != nil {
		if *stateID == uuid.Nil {
			return nil, errors.New("invalid state id")
		}
		newStateID = *stateID
	}

	newName := existingCity.Name
	if name != nil {
		newName = *name
	}

	updatedCity, err := database.Queries.UpdateCity(ctx, db.UpdateCityParams{
		ID:      id,
		StateID: newStateID,
		Name:    newName,
	})
	if err != nil {
		return nil, err
	}

	return &updatedCity, nil
}

// DeleteCity is the resolver for the deleteCity field.
func (r *mutationResolver) DeleteCity(ctx context.Context, id uuid.UUID) (*db.City, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid city id")
	}

	// Call SQL query to delete city
	city, err := database.Queries.DeleteCity(ctx, id)
	if err != nil {
		return nil, err
	}

	return &city, nil
}

// City is the resolver for the city field.
func (r *queryResolver) City(ctx context.Context, id uuid.UUID) (*db.City, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid city id")
	}

	city, err := database.Queries.GetCity(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.New("city not found")
		}
		return nil, err
	}

	return &city, nil
}

// Cities is the resolver for the cities field.
func (r *queryResolver) Cities(ctx context.Context) ([]*db.City, error) {
	cities, err := database.Queries.ListCities(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*db.City, 0, len(cities))
	for _, city := range cities {
		c := city // avoid pointer reuse bug
		result = append(result, &c)
	}

	return result, nil
}

// CitiesByState is the resolver for the citiesByState field.
func (r *queryResolver) CitiesByState(ctx context.Context, stateID uuid.UUID) ([]*db.City, error) {
	if stateID == uuid.Nil {
		return nil, errors.New("invalid state id")
	}

	cities, err := database.Queries.ListCitiesByState(ctx, stateID)
	if err != nil {
		return nil, err
	}

	result := make([]*db.City, 0, len(cities))
	for _, city := range cities {
		c := city // avoid pointer reuse bug
		result = append(result, &c)
	}

	return result, nil
}
