package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/internal/db"
	"strconv"
)

// CreateCountry is the resolver for the createCountry field.
func (r *mutationResolver) CreateCountry(ctx context.Context, name string) (*db.Country, error) {
	if name == "" {
		return nil, errors.New("name is required")
	}

	// Call the database query
	countryDB, err := database.Queries.CreateCountry(ctx, name)
	if err != nil {
		return nil, err
	}

	return &countryDB, nil
}

// UpdateCountry is the resolver for the updateCountry field.
func (r *mutationResolver) UpdateCountry(ctx context.Context, id string, name *string) (*db.Country, error) {
	// Convert ID
	countryID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid country id")
	}

	// Handle optional name
	updateName := ""
	if name != nil {
		updateName = *name
	}

	// Call sqlc update query
	countryDB, err := database.Queries.UpdateCountry(ctx, db.UpdateCountryParams{
		Name: updateName,
		ID:   int32(countryID),
	})
	if err != nil {
		return nil, err
	}

	return &countryDB, nil
}

// DeleteCountry is the resolver for the deleteCountry field.
func (r *mutationResolver) DeleteCountry(ctx context.Context, id string) (*db.Country, error) {
	// Convert ID from string → int
	countryID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid country id")
	}

	// Call sqlc delete query
	countryDB, err := database.Queries.DeleteCountry(ctx, int32(countryID))
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.New("country not found")
		}
		return nil, err
	}

	return &countryDB, nil
}

// Country is the resolver for the country field.
func (r *queryResolver) Country(ctx context.Context, id string) (*db.Country, error) {
	// Convert GraphQL ID (string) → int
	countryID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid country id")
	}

	// Fetch country from database
	countryDB, err := database.Queries.GetCountry(ctx, int32(countryID))
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.New("country not found")
		}
		return nil, err
	}

	return &countryDB, nil
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context) ([]*db.Country, error) {
	countriesDB, err := database.Queries.ListCountries(ctx)
	if err != nil {
		return nil, err
	}

	// Convert []Country → []*Country
	countries := make([]*db.Country, len(countriesDB))
	for i := range countriesDB {
		countries[i] = &countriesDB[i]
	}

	return countries, nil
}
