package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"graphql/graphql/models"
	"graphql/internal/mail"
	"log"
	"time"
)

// SubmitInquiry is the resolver for the submitInquiry field.
func (r *mutationResolver) SubmitInquiry(ctx context.Context, input models.InquiryInput) (*models.InquiryResult, error) {
	refId := time.Now().Format("20060102-150405")

	// Company gets inquiry
	if err := mail.SendInquiryEmail(input.FullName, input.Email, input.Phone, input.Destination, input.Message); err != nil {
		log.Printf("Admin email error: %v", err)
	}

	// User gets confirmation → YOUR GMAIL
	if err := mail.SendUserConfirmationEmail(input.Email, input.FullName, input.Destination); err != nil {
		log.Printf("User email error: %v", err)
	}

	return &models.InquiryResult{
		Success: true,
		RefID:   refId,
	}, nil
}
