package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/db"
	"strconv"
)

// CreatePackage is the resolver for the createPackage field.
func (r *mutationResolver) CreatePackage(ctx context.Context, tourID string, packageName string, price string, currency string, occupancy *string, isFeatured *bool, images []*models.PackageImageInput) (*db.Package, error) {
	if tourID == "" || packageName == "" || price == "" || currency == "" {
		return nil, errors.New("tour_id, package_name, price and currency are required")
	}

	tID, err := strconv.Atoi(tourID)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	var occ sql.NullString
	if occupancy != nil {
		occ = sql.NullString{String: *occupancy, Valid: true}
	}

	feat := false
	if isFeatured != nil {
		feat = *isFeatured
	}

	// 1) Package create
	pkg, err := database.Queries.CreatePackage(ctx, db.CreatePackageParams{
		TourID:      int32(tID),
		PackageName: packageName,
		Price:       price,
		Currency:    currency,
		Occupancy:   occ,
		IsFeatured:  feat,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images insert (SAME AS TOUR)
	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		var alt sql.NullString
		if img.AltText != nil {
			alt = sql.NullString{String: *img.AltText, Valid: true}
		}

		_, err := database.Queries.CreatePackageImage(ctx, db.CreatePackageImageParams{
			PackageID: pkg.ID,
			FileUrl:   img.FileURL,
			AltText:   alt,
		})
		if err != nil {
			return nil, err
		}
	}

	return &pkg, nil
}

// UpdatePackage is the resolver for the updatePackage field.
func (r *mutationResolver) UpdatePackage(ctx context.Context, id string, tourID *string, packageName *string, price *string, currency *string, occupancy *string, isFeatured *bool, images []*models.PackageImageInput) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	// existing row for defaults
	existing, err := database.Queries.GetPackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	newTourID := existing.TourID
	if tourID != nil {
		tid, err := strconv.Atoi(*tourID)
		if err != nil {
			return nil, errors.New("invalid tour id")
		}
		newTourID = int32(tid)
	}

	newName := existing.PackageName
	if packageName != nil {
		newName = *packageName
	}

	newPrice := existing.Price
	if price != nil {
		newPrice = *price
	}

	newCurrency := existing.Currency
	if currency != nil {
		newCurrency = *currency
	}

	newOcc := existing.Occupancy
	if occupancy != nil {
		newOcc = sql.NullString{String: *occupancy, Valid: true}
	}

	newFeatured := existing.IsFeatured
	if isFeatured != nil {
		newFeatured = *isFeatured
	}

	// 1) Package update
	pkg, err := database.Queries.UpdatePackage(ctx, db.UpdatePackageParams{
		ID:          int32(pkgID),
		TourID:      newTourID,
		PackageName: newName,
		Price:       newPrice,
		Currency:    newCurrency,
		Occupancy:   newOcc,
		IsFeatured:  newFeatured,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images argument diya ho to replace karo (SAME AS TOUR)
	if images != nil {
		// Purane saare images delete
		if err := database.Queries.DeletePackageImagesByPackage(ctx, pkg.ID); err != nil {
			return nil, err
		}

		// Naye insert
		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			var alt sql.NullString
			if img.AltText != nil {
				alt = sql.NullString{String: *img.AltText, Valid: true}
			}

			_, err := database.Queries.CreatePackageImage(ctx, db.CreatePackageImageParams{
				PackageID: pkg.ID,
				FileUrl:   img.FileURL,
				AltText:   alt,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	return &pkg, nil
}

// DeletePackage is the resolver for the deletePackage field.
func (r *mutationResolver) DeletePackage(ctx context.Context, id string) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	pkg, err := database.Queries.DeletePackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// ID is the resolver for the id field.
func (r *packageResolver) ID(ctx context.Context, obj *db.Package) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// TourID is the resolver for the tour_id field.
func (r *packageResolver) TourID(ctx context.Context, obj *db.Package) (string, error) {
	return fmt.Sprintf("%d", obj.TourID), nil
}

// Occupancy is the resolver for the occupancy field.
func (r *packageResolver) Occupancy(ctx context.Context, obj *db.Package) (*string, error) {
	if !obj.Occupancy.Valid {
		return nil, nil
	}
	occ := obj.Occupancy.String
	return &occ, nil
}

// Images is the resolver for the images field.
func (r *packageResolver) Images(ctx context.Context, obj *db.Package) ([]*db.PackageImage, error) {
	imgs, err := database.Queries.ListPackageImagesByPackage(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	// sqlc likely returns []db.PackageImage, gqlgen ko []*db.PackageImage chahiye
	out := make([]*db.PackageImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// ID is the resolver for the id field.
func (r *packageImageResolver) ID(ctx context.Context, obj *db.PackageImage) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// PackageID is the resolver for the package_id field.
func (r *packageImageResolver) PackageID(ctx context.Context, obj *db.PackageImage) (string, error) {
	return fmt.Sprintf("%d", obj.PackageID), nil
}

// AltText is the resolver for the alt_text field.
func (r *packageImageResolver) AltText(ctx context.Context, obj *db.PackageImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// Package is the resolver for the package field.
func (r *queryResolver) Package(ctx context.Context, id string) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	pkg, err := database.Queries.GetPackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// Packages is the resolver for the packages field.
func (r *queryResolver) Packages(ctx context.Context) ([]*db.Package, error) {
	pkgsDB, err := database.Queries.ListPackages(ctx)
	if err != nil {
		return nil, err
	}

	pkgs := make([]*db.Package, 0, len(pkgsDB))
	for i := range pkgsDB {
		p := pkgsDB[i]
		pkgs = append(pkgs, &p)
	}
	return pkgs, nil
}

// PackagesByTour is the resolver for the packagesByTour field.
func (r *queryResolver) PackagesByTour(ctx context.Context, tourID string) ([]*db.Package, error) {
	tID, err := strconv.Atoi(tourID)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	pkgsDB, err := database.Queries.ListPackagesByTour(ctx, int32(tID))
	if err != nil {
		return nil, err
	}

	pkgs := make([]*db.Package, 0, len(pkgsDB))
	for i := range pkgsDB {
		p := pkgsDB[i]
		pkgs = append(pkgs, &p)
	}
	return pkgs, nil
}

// PackageImage is the resolver for the packageImage field.
func (r *queryResolver) PackageImage(ctx context.Context, id string) (*db.PackageImage, error) {
	imgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid image id")
	}

	img, err := database.Queries.GetPackageImageByID(ctx, int32(imgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("image not found")
	}
	if err != nil {
		return nil, err
	}

	return &img, nil
}

// Package returns generated.PackageResolver implementation.
func (r *Resolver) Package() generated.PackageResolver { return &packageResolver{r} }

// PackageImage returns generated.PackageImageResolver implementation.
func (r *Resolver) PackageImage() generated.PackageImageResolver { return &packageImageResolver{r} }

type packageResolver struct{ *Resolver }
type packageImageResolver struct{ *Resolver }
