type Package {
  id: UUID!
  tour_id: UUID!
  package_name: String!
  price: String!
  currency: String!
  occupancy: String
  is_featured: Boolean
  created_at: Time!
  updated_at: Time!
  images: [PackageImage!]!

  tour: Tour
}

type PackageImage {
  id: UUID!
  package_id: UUID!
  file_url: String!
  alt_text: String
  created_at: Time!
  updated_at: Time!
}

input PackageImageInput {
  file_url: String!
  alt_text: String
}

extend type Query {
  package(id: UUID!): Package
  packages: [Package!]!
  packagesByTour(tour_id: UUID!): [Package!]!
  packageImage(id: UUID!): PackageImage!
}

extend type Mutation {
  createPackage(
    tour_id: UUID!
    package_name: String!
    price: String!
    currency: String!
    occupancy: String
    is_featured: Boolean
    images: [PackageImageInput!]
  ): Package!

  updatePackage(
    id: UUID!
    tour_id: UUID
    package_name: String
    price: String
    currency: String
    occupancy: String
    is_featured: Boolean
    images: [PackageImageInput!]
  ): Package!

  deletePackage(id: UUID!): Package!
}
