package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/internal/db"
	"strconv"
)

// CreatePackage is the resolver for the createPackage field.
func (r *mutationResolver) CreatePackage(ctx context.Context, tourID string, packageName string, price string, currency string, occupancy *string, isFeatured *bool) (*db.Package, error) {
	if tourID == "" || packageName == "" || price == "" || currency == "" {
		return nil, errors.New("tour_id, package_name, price and currency are required")
	}

	tID, err := strconv.Atoi(tourID)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	var occ sql.NullString
	if occupancy != nil {
		occ = sql.NullString{String: *occupancy, Valid: true}
	}

	feat := false
	if isFeatured != nil {
		feat = *isFeatured
	}

	pkg, err := database.Queries.CreatePackage(ctx, db.CreatePackageParams{
		TourID:      int32(tID),
		PackageName: packageName,
		Price:       price,
		Currency:    currency,
		Occupancy:   occ,
		IsFeatured:  feat,
	})
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// UpdatePackage is the resolver for the updatePackage field.
func (r *mutationResolver) UpdatePackage(ctx context.Context, id string, tourID *string, packageName *string, price *string, currency *string, occupancy *string, isFeatured *bool) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	// existing row for defaults
	existing, err := database.Queries.GetPackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	newTourID := existing.TourID
	if tourID != nil {
		tid, err := strconv.Atoi(*tourID)
		if err != nil {
			return nil, errors.New("invalid tour id")
		}
		newTourID = int32(tid)
	}

	newName := existing.PackageName
	if packageName != nil {
		newName = *packageName
	}

	newPrice := existing.Price
	if price != nil {
		newPrice = *price
	}

	newCurrency := existing.Currency
	if currency != nil {
		newCurrency = *currency
	}

	newOcc := existing.Occupancy
	if occupancy != nil {
		newOcc = sql.NullString{String: *occupancy, Valid: true}
	}

	newFeatured := existing.IsFeatured
	if isFeatured != nil {
		newFeatured = *isFeatured
	}

	pkg, err := database.Queries.UpdatePackage(ctx, db.UpdatePackageParams{
		ID:          int32(pkgID),
		TourID:      newTourID,
		PackageName: newName,
		Price:       newPrice,
		Currency:    newCurrency,
		Occupancy:   newOcc,
		IsFeatured:  newFeatured,
	})
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// DeletePackage is the resolver for the deletePackage field.
func (r *mutationResolver) DeletePackage(ctx context.Context, id string) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	pkg, err := database.Queries.DeletePackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// TourID is the resolver for the tour_id field.
func (r *packageResolver) TourID(ctx context.Context, obj *db.Package) (string, error) {
	return fmt.Sprintf("%d", obj.TourID), nil
}

// Occupancy is the resolver for the occupancy field.
func (r *packageResolver) Occupancy(ctx context.Context, obj *db.Package) (*string, error) {
	if !obj.Occupancy.Valid {
		return nil, nil
	}
	occ := obj.Occupancy.String
	return &occ, nil
}

// / Package is the resolver for the package field.
func (r *queryResolver) Package(ctx context.Context, id string) (*db.Package, error) {
	pkgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid package id")
	}

	pkg, err := database.Queries.GetPackage(ctx, int32(pkgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("package not found")
	}
	if err != nil {
		return nil, err
	}

	return &pkg, nil
}

// Packages is the resolver for the packages field.
func (r *queryResolver) Packages(ctx context.Context) ([]*db.Package, error) {
	pkgsDB, err := database.Queries.ListPackages(ctx)
	if err != nil {
		return nil, err
	}

	pkgs := make([]*db.Package, 0, len(pkgsDB))
	for i := range pkgsDB {
		p := pkgsDB[i]
		pkgs = append(pkgs, &p)
	}
	return pkgs, nil
}

// PackagesByTour is the resolver for the packagesByTour field.
func (r *queryResolver) PackagesByTour(ctx context.Context, tourID string) ([]*db.Package, error) {
	tID, err := strconv.Atoi(tourID)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	pkgsDB, err := database.Queries.ListPackagesByTour(ctx, int32(tID))
	if err != nil {
		return nil, err
	}

	pkgs := make([]*db.Package, 0, len(pkgsDB))
	for i := range pkgsDB {
		p := pkgsDB[i]
		pkgs = append(pkgs, &p)
	}
	return pkgs, nil
}
