package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/adapter"
	"graphql/internal/auth"
	"graphql/internal/db"
	dbtime "graphql/internal/dbTime"
	appErr "graphql/internal/errors"
	"graphql/internal/validation"
	"strings"

	"github.com/google/uuid"
)

// CreatePoi is the resolver for the createPOI field.
func (r *mutationResolver) CreatePoi(ctx context.Context, name string, description *string, cityID uuid.UUID, typeArg string, images []*models.POIImageInput) (*db.PointsOfInterest, error) {
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// Auth function
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}

	// ---- BASIC VALIDATION ----
	if name == "" || cityID == uuid.Nil || typeArg == "" {
		return nil, appErr.InvalidInput()
	}

	// normalize
	typeArg = strings.ToLower(strings.TrimSpace(typeArg))

	valid := map[string]struct{}{
		"landmark":   {},
		"hotel":      {},
		"restaurant": {},
		"activity":   {},
		"transport":  {},
	}

	if _, ok := valid[typeArg]; !ok {
		return nil, appErr.InvalidInput()
	}

	// var desc sql.NullString
	// if description != nil {
	// desc = sql.NullString{String: *description, Valid: true}
	desc := adapter.NullString(description)

	// }

	// ---- START TRANSACTION ----
	tx, err := database.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}

	// qtx := database.New(tx)
	qtx := db.New(tx)

	// ---- CITY VALIDATION (CENTRALIZED) ----
	if err := validation.ValidateCityID(ctx, qtx, cityID); err != nil {
		tx.Rollback()
		return nil, err
	}

	// ---- CREATE POI ----
	poi, err := qtx.CreatePOI(ctx, db.CreatePOIParams{
		Name:        name,
		Description: desc,
		CityID:      cityID,
		Type:        typeArg,
	})
	if err != nil {
		tx.Rollback()
		return nil, appErr.FromDB(err)
	}

	// ---- CREATE IMAGES ----
	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		// var alt sql.NullString
		// if img.AltText != nil {
		// alt = sql.NullString{String: *img.AltText, Valid: true}
		alt := adapter.NullString(img.AltText)

		// }

		_, err := qtx.CreatePOIImage(ctx, db.CreatePOIImageParams{
			PoiID:   poi.ID,
			FileUrl: img.FileURL,
			AltText: alt,
		})
		if err != nil {
			tx.Rollback()
			return nil, appErr.Internal(err)
		}
	}

	// ---- COMMIT ----
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return &poi, nil
}

// UpdatePoi is the resolver for the updatePOI field.
func (r *mutationResolver) UpdatePoi(ctx context.Context, id uuid.UUID, name *string, description *string, cityID *uuid.UUID, typeArg *string, images []*models.POIImageInput) (*db.PointsOfInterest, error) {
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()

	// Auth function
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	if err := adapter.ValidateUUID(id); err != nil {
		return nil, appErr.InvalidInput()
	}

	// ---- START TRANSACTION ----
	tx, err := database.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	qtx := db.New(tx)

	// ---- GET EXISTING POI ----
	existing, err := qtx.GetPOI(ctx, id)
	if err != nil {
		tx.Rollback()
		return nil, appErr.FromDB(err)
	}

	// ---- MERGE FIELDS ----
	newName := existing.Name
	if name != nil {
		newName = *name
	}

	newDesc := existing.Description
	if description != nil {
		newDesc = adapter.NullString(description)
	}

	newCityID := existing.CityID
	if cityID != nil {
		if err := validation.ValidateCityID(ctx, qtx, *cityID); err != nil {
			tx.Rollback()
			return nil, err
		}
		newCityID = *cityID
	}

	newType := existing.Type

	if typeArg != nil {
		t := strings.ToLower(strings.TrimSpace(*typeArg))

		valid := map[string]struct{}{
			"landmark":   {},
			"hotel":      {},
			"restaurant": {},
			"activity":   {},
			"transport":  {},
		}

		if _, ok := valid[t]; !ok {
			return nil, appErr.InvalidInput()
		}

		newType = t
	}

	// ---- UPDATE POI ----
	poi, err := qtx.UpdatePOI(ctx, db.UpdatePOIParams{
		ID:          id,
		Name:        newName,
		Description: newDesc,
		CityID:      newCityID,
		Type:        newType,
	})
	if err != nil {
		tx.Rollback()
		return nil, appErr.FromDB(err)
	}

	// ---- UPDATE IMAGES (ATOMIC) ----
	if images != nil {
		if err := qtx.DeletePOIImagesByPOI(ctx, poi.ID); err != nil {
			tx.Rollback()
			return nil, err
		}

		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			// var alt sql.NullString
			// if img.AltText != nil {
			alt := adapter.NullString(img.AltText)

			// }

			_, err := qtx.CreatePOIImage(ctx, db.CreatePOIImageParams{
				PoiID:   poi.ID,
				FileUrl: img.FileURL,
				AltText: alt,
			})
			if err != nil {
				tx.Rollback()
				return nil, err
			}
		}
	}

	// ---- COMMIT ----
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return &poi, nil
}

// DeletePoi is the resolver for the deletePOI field.
func (r *mutationResolver) DeletePoi(ctx context.Context, id uuid.UUID) (*db.PointsOfInterest, error) {
	// Auth function
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}

	if err := adapter.ValidateUUID(id); err != nil {
		return nil, appErr.InvalidInput()
	}

	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()

	poi, err := database.Queries.DeletePOI(ctx, id)
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	return &poi, nil
}

// Description is the resolver for the description field.
func (r *pOIResolver) Description(ctx context.Context, obj *db.PointsOfInterest) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	v := obj.Description.String
	return &v, nil
}

// Images is the resolver for the images field.
func (r *pOIResolver) Images(ctx context.Context, obj *db.PointsOfInterest) ([]*db.PoiImage, error) {
	imgs, err := database.Queries.ListPOIImagesByPOI(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.PoiImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// AltText is the resolver for the alt_text field.
func (r *pOIImageResolver) AltText(ctx context.Context, obj *db.PoiImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// Poi is the resolver for the poi field.
func (r *queryResolver) Poi(ctx context.Context, id uuid.UUID) (*db.PointsOfInterest, error) {
	if err := adapter.ValidateUUID(id); err != nil {
		return nil, appErr.InvalidInput()
	}

	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()

	poi, err := database.Queries.GetPOI(ctx, id)
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	return &poi, nil
}

// Pois is the resolver for the pois field.
func (r *queryResolver) Pois(ctx context.Context, limit *int, offset *int) ([]*db.PointsOfInterest, error) {
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// ---- DEFAULTS ----
	var l int32 = 20
	var o int32 = 0

	if limit != nil && *limit > 0 {
		l = int32(*limit)
	}
	if offset != nil && *offset >= 0 {
		o = int32(*offset)
	}

	poisDB, err := database.Queries.ListPOIs(ctx, db.ListPOIsParams{
		Limit:  l,
		Offset: o,
	})
	if err != nil {
		return nil, appErr.Internal(err)
	}

	out := make([]*db.PointsOfInterest, 0, len(poisDB))
	for i := range poisDB {
		p := poisDB[i]
		out = append(out, &p)
	}

	return out, nil
}

// PoisByCity is the resolver for the poisByCity field.
func (r *queryResolver) PoisByCity(ctx context.Context, cityID uuid.UUID) ([]*db.PointsOfInterest, error) {
	if err := adapter.ValidateUUID(cityID); err != nil {
		return nil, appErr.InvalidInput()
	}

	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	poisDB, err := database.Queries.ListPOIsByCity(ctx, cityID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.PointsOfInterest, 0, len(poisDB))
	for i := range poisDB {
		p := poisDB[i]
		out = append(out, &p)
	}
	return out, nil
}

// PoiImage is the resolver for the poiImage field.
func (r *queryResolver) PoiImage(ctx context.Context, id uuid.UUID) (*db.PoiImage, error) {
	if err := adapter.ValidateUUID(id); err != nil {
		return nil, appErr.InvalidInput()
	}

	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	img, err := database.Queries.GetPOIImageByID(ctx, id)
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	return &img, nil
}

// POI returns generated.POIResolver implementation.
func (r *Resolver) POI() generated.POIResolver { return &pOIResolver{r} }

// POIImage returns generated.POIImageResolver implementation.
func (r *Resolver) POIImage() generated.POIImageResolver { return &pOIImageResolver{r} }

type pOIResolver struct{ *Resolver }
type pOIImageResolver struct{ *Resolver }
