type POI {
  id: UUID!
  name: String!
  description: String
  city_id: UUID!
  type: String!
  created_at: Time!
  updated_at: Time!
  images: [POIImage!]!

  city: City
}

type POIImage {
  id: UUID!
  poi_id: UUID!
  file_url: String!
  alt_text: String
  created_at: Time!
  updated_at: Time!
}

input POIImageInput {
  file_url: String!
  alt_text: String
}

extend type Query {
  poi(id: UUID!): POI
  pois: [POI!]!
  poisByCity(city_id: UUID!): [POI!]!
  poiImage(id: UUID!): POIImage!
}

extend type Mutation {
  createPOI(
    name: String!
    description: String
    city_id: UUID!
    type: String!
    images: [POIImageInput!]
  ): POI!

  updatePOI(
    id: UUID!
    name: String
    description: String
    city_id: UUID
    type: String
    images: [POIImageInput!]
  ): POI!

  deletePOI(id: UUID!): POI!
}
