package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/db"

	"github.com/google/uuid"
)

// CreatePoi is the resolver for the createPOI field.
func (r *mutationResolver) CreatePoi(ctx context.Context, name string, description *string, cityID uuid.UUID, typeArg string, images []*models.POIImageInput) (*db.PointsOfInterest, error) {
	if name == "" || cityID == uuid.Nil || typeArg == "" {
		return nil, errors.New("name, city_id and type are required")
	}

	if cityID == uuid.Nil {
		return nil, errors.New("invalid city id")
	}

	var desc sql.NullString
	if description != nil {
		desc = sql.NullString{String: *description, Valid: true}
	}

	poi, err := database.Queries.CreatePOI(ctx, db.CreatePOIParams{
		Name:        name,
		Description: desc,
		CityID:      cityID,
		Type:        typeArg,
	})
	if err != nil {
		return nil, err
	}

	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		var alt sql.NullString
		if img.AltText != nil {
			alt = sql.NullString{String: *img.AltText, Valid: true}
		}

		_, err := database.Queries.CreatePOIImage(ctx, db.CreatePOIImageParams{
			PoiID:   poi.ID,
			FileUrl: img.FileURL,
			AltText: alt,
		})
		if err != nil {
			return nil, err
		}
	}

	return &poi, nil
}

// UpdatePoi is the resolver for the updatePOI field.
func (r *mutationResolver) UpdatePoi(ctx context.Context, id uuid.UUID, name *string, description *string, cityID *uuid.UUID, typeArg *string, images []*models.POIImageInput) (*db.PointsOfInterest, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid poi id")
	}

	existing, err := database.Queries.GetPOI(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("poi not found")
	}
	if err != nil {
		return nil, err
	}

	newName := existing.Name
	if name != nil {
		newName = *name
	}

	newDesc := existing.Description
	if description != nil {
		newDesc = sql.NullString{String: *description, Valid: true}
	}

	newCityID := existing.CityID
	if cityID != nil {
		if *cityID == uuid.Nil {
			return nil, errors.New("invalid city id")
		}
		newCityID = *cityID
	}

	newType := existing.Type
	if typeArg != nil {
		newType = *typeArg
	}

	poi, err := database.Queries.UpdatePOI(ctx, db.UpdatePOIParams{
		ID:          id,
		Name:        newName,
		Description: newDesc,
		CityID:      newCityID,
		Type:        newType,
	})
	if err != nil {
		return nil, err
	}

	if images != nil {
		if err := database.Queries.DeletePOIImagesByPOI(ctx, poi.ID); err != nil {
			return nil, err
		}

		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			var alt sql.NullString
			if img.AltText != nil {
				alt = sql.NullString{String: *img.AltText, Valid: true}
			}

			_, err := database.Queries.CreatePOIImage(ctx, db.CreatePOIImageParams{
				PoiID:   poi.ID,
				FileUrl: img.FileURL,
				AltText: alt,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	return &poi, nil
}

// DeletePoi is the resolver for the deletePOI field.
func (r *mutationResolver) DeletePoi(ctx context.Context, id uuid.UUID) (*db.PointsOfInterest, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid poi id")
	}

	poi, err := database.Queries.DeletePOI(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("poi not found")
	}
	if err != nil {
		return nil, err
	}

	return &poi, nil
}

// Description is the resolver for the description field.
func (r *pOIResolver) Description(ctx context.Context, obj *db.PointsOfInterest) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	v := obj.Description.String
	return &v, nil
}

// Images is the resolver for the images field.
func (r *pOIResolver) Images(ctx context.Context, obj *db.PointsOfInterest) ([]*db.PointOfInterestImage, error) {
	imgs, err := database.Queries.ListPOIImagesByPOI(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.PointOfInterestImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// AltText is the resolver for the alt_text field.
func (r *pOIImageResolver) AltText(ctx context.Context, obj *db.PointOfInterestImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// Poi is the resolver for the poi field.
func (r *queryResolver) Poi(ctx context.Context, id uuid.UUID) (*db.PointsOfInterest, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid poi id")
	}

	poi, err := database.Queries.GetPOI(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("poi not found")
	}
	if err != nil {
		return nil, err
	}

	return &poi, nil
}

// Pois is the resolver for the pois field.
func (r *queryResolver) Pois(ctx context.Context) ([]*db.PointsOfInterest, error) {
	poisDB, err := database.Queries.ListPOIs(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*db.PointsOfInterest, 0, len(poisDB))
	for i := range poisDB {
		p := poisDB[i]
		out = append(out, &p)
	}
	return out, nil
}

// PoisByCity is the resolver for the poisByCity field.
func (r *queryResolver) PoisByCity(ctx context.Context, cityID uuid.UUID) ([]*db.PointsOfInterest, error) {
	if cityID == uuid.Nil {
		return nil, errors.New("invalid city id")
	}

	poisDB, err := database.Queries.ListPOIsByCity(ctx, cityID)
	if err != nil {
		return nil, err
	}

	out := make([]*db.PointsOfInterest, 0, len(poisDB))
	for i := range poisDB {
		p := poisDB[i]
		out = append(out, &p)
	}
	return out, nil
}

// PoiImage is the resolver for the poiImage field.
func (r *queryResolver) PoiImage(ctx context.Context, id uuid.UUID) (*db.PointOfInterestImage, error) {
	if id == uuid.Nil {
		return nil, errors.New("invalid image id")
	}

	img, err := database.Queries.GetPOIImageByID(ctx, id)
	if err == sql.ErrNoRows {
		return nil, errors.New("image not found")
	}
	if err != nil {
		return nil, err
	}

	return &img, nil
}

// POI returns generated.POIResolver implementation.
func (r *Resolver) POI() generated.POIResolver { return &pOIResolver{r} }

// POIImage returns generated.POIImageResolver implementation.
func (r *Resolver) POIImage() generated.POIImageResolver { return &pOIImageResolver{r} }

type pOIResolver struct{ *Resolver }
type pOIImageResolver struct{ *Resolver }
