package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"database/sql"
	"errors"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/internal/db"
	"graphql/models"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, fullName string, email string, password string, phone *string) (*models.User, error) {
	if fullName == "" || email == "" || password == "" {
		return nil, errors.New("full_name, email, and password are required")
	}

	var phoneVal sql.NullString
	if phone != nil {
		phoneVal = sql.NullString{String: *phone, Valid: true}
	}

	userDB, err := database.Queries.CreateUser(ctx, db.CreateUserParams{
		FullName: fullName,
		Email:    email,
		Password: password,
		Phone:    phoneVal,
	})
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, fullName *string, email *string, password *string, phone *string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	if fullName == nil && email == nil && password == nil && phone == nil {
		return nil, errors.New("at least one field must be provided for update")
	}

	params := db.UpdateUserParams{
		ID: int32(userID),
	}

	if fullName != nil {
		params.FullName = sql.NullString{String: *fullName, Valid: true}
	}
	if email != nil {
		params.Email = sql.NullString{String: *email, Valid: true}
	}
	if password != nil {
		params.Password = sql.NullString{String: *password, Valid: true}
	}
	if phone != nil {
		params.Phone = sql.NullString{String: *phone, Valid: true}
	}

	userDB, err := database.Queries.UpdateUser(ctx, params)
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	userDB, err := database.Queries.DeleteUser(ctx, int32(userID))
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	userDB, err := database.Queries.GetUser(ctx, int32(userID))
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	usersDB, err := database.Queries.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return database.ToModelUsers(usersDB), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
