package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"

	"graphql/database"
	"graphql/graphql/generated"
	models1 "graphql/graphql/models"
	"graphql/internal/db"
	"graphql/models"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, fullName string, email string, password string, phone *string) (*models.User, error) {
	if fullName == "" || email == "" || password == "" {
		return nil, errors.New("full_name, email, and password are required")
	}

	var phoneVal sql.NullString
	if phone != nil {
		phoneVal = sql.NullString{String: *phone, Valid: true}
	}

	// Hash the password before storing
	hashed, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}

	userDB, err := database.Queries.CreateUser(ctx, db.CreateUserParams{
		FullName: fullName,
		Email:    email,
		Password: string(hashed),
		Phone:    phoneVal,
	})
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, fullName *string, email *string, password *string, phone *string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	if fullName == nil && email == nil && password == nil && phone == nil {
		return nil, errors.New("at least one field must be provided for update")
	}

	params := db.UpdateUserParams{
		ID: int32(userID),
	}

	if fullName != nil {
		params.FullName = sql.NullString{String: *fullName, Valid: true}
	}
	if email != nil {
		params.Email = sql.NullString{String: *email, Valid: true}
	}
	if password != nil {
		// Hash updated password
		hashed, err := bcrypt.GenerateFromPassword([]byte(*password), bcrypt.DefaultCost)
		if err != nil {
			return nil, err
		}
		params.Password = sql.NullString{String: string(hashed), Valid: true}
	}
	if phone != nil {
		params.Phone = sql.NullString{String: *phone, Valid: true}
	}

	userDB, err := database.Queries.UpdateUser(ctx, params)
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	userDB, err := database.Queries.DeleteUser(ctx, int32(userID))
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*models1.LoginResponse, error) {
	// Lookup user by email
	var (
		id        int32
		fullName  string
		em        string
		storedPwd string
		phone     sql.NullString
		roleID    sql.NullInt32
		createdAt time.Time
		updatedAt time.Time
	)

	err := database.DB.QueryRowContext(ctx, `SELECT id, full_name, email, password, phone, role_id, created_at, updated_at FROM users WHERE email = $1`, email).Scan(
		&id, &fullName, &em, &storedPwd, &phone, &roleID, &createdAt, &updatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, errors.New("invalid credentials")
	}
	if err != nil {
		return nil, err
	}

	// Verify password (support bcrypt hashes and plaintext)
	ok := false
	if strings.HasPrefix(storedPwd, "$2a$") || strings.HasPrefix(storedPwd, "$2b$") || strings.HasPrefix(storedPwd, "$2y$") {
		if bcrypt.CompareHashAndPassword([]byte(storedPwd), []byte(password)) == nil {
			ok = true
		}
	} else {
		if storedPwd == password {
			ok = true
			// re-hash and store
			if hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost); err == nil {
				_, _ = database.DB.ExecContext(ctx, `UPDATE users SET password = $1 WHERE id = $2`, string(hash), id)
			}
		}
	}

	if !ok {
		return nil, errors.New("invalid credentials")
	}

	// create JWT
	secret := os.Getenv("JWT_SECRET")
	if secret == "" {
		secret = "devsecret"
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"sub": fmt.Sprintf("%d", id),
		"exp": time.Now().Add(24 * time.Hour).Unix(),
	})
	tokenStr, err := token.SignedString([]byte(secret))
	if err != nil {
		return nil, err
	}

	user := database.ToModelUser(db.User{
		ID:        id,
		FullName:  fullName,
		Email:     em,
		Password:  storedPwd,
		Phone:     phone,
		RoleID:    roleID,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	})

	return &models1.LoginResponse{Token: tokenStr, User: user}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	userDB, err := database.Queries.GetUser(ctx, int32(userID))
	if err == sql.ErrNoRows {
		return nil, errors.New("user not found")
	}
	if err != nil {
		return nil, err
	}

	return database.ToModelUser(db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	usersDB, err := database.Queries.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return database.ToModelUsers(usersDB), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
