package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/internal/db"
	"strconv"
)

// CreateState is the resolver for the createState field.
func (r *mutationResolver) CreateState(ctx context.Context, countryID string, name string) (*db.State, error) {
	if name == "" {
		return nil, errors.New("state name is required")
	}

	// Parse country ID
	cID, err := strconv.Atoi(countryID)
	if err != nil {
		return nil, errors.New("invalid country id")
	}

	state, err := database.Queries.CreateState(ctx, db.CreateStateParams{
		CountryID: int32(cID),
		Name:      name,
	})
	if err != nil {
		return nil, err
	}

	return &state, nil
}

// UpdateState is the resolver for the updateState field.
func (r *mutationResolver) UpdateState(ctx context.Context, id string, countryID *string, name *string) (*db.State, error) {
	stateID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid state ID")
	}

	existing, err := database.Queries.GetState(ctx, int32(stateID))
	if err != nil {
		return nil, err
	}

	// Resolve country ID
	updateCountryID := existing.CountryID
	if countryID != nil {
		parsedID, err := strconv.Atoi(*countryID)
		if err != nil {
			return nil, errors.New("invalid country ID")
		}
		updateCountryID = int32(parsedID)
	}

	// Resolve name
	updateName := existing.Name
	if name != nil {
		updateName = *name
	}

	state, err := database.Queries.UpdateState(ctx, db.UpdateStateParams{
		CountryID: updateCountryID,
		Name:      updateName,
		ID:        int32(stateID),
	})
	if err != nil {
		return nil, err
	}

	return &state, nil
}

// DeleteState is the resolver for the deleteState field.
func (r *mutationResolver) DeleteState(ctx context.Context, id string) (*db.State, error) {
	stateID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid state id")
	}

	state, err := database.Queries.DeleteState(ctx, int32(stateID))
	return &state, err
}

// State is the resolver for the state field.
func (r *queryResolver) State(ctx context.Context, id string) (*db.State, error) {
	stateID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid state id")
	}

	state, err := database.Queries.GetState(ctx, int32(stateID))
	if err == sql.ErrNoRows {
		return nil, nil
	}

	return &state, err
}

// States is the resolver for the states field.
func (r *queryResolver) States(ctx context.Context) ([]*db.State, error) {
	states, err := database.Queries.ListStates(ctx)
	if err != nil {
		return nil, err
	}
	var result []*db.State
	for _, s := range states {
		state := s
		result = append(result, &state)
	}

	return result, nil
}

// StatesByCountry is the resolver for the statesByCountry field.
func (r *queryResolver) StatesByCountry(ctx context.Context, countryID string) ([]*db.State, error) {
	id, err := strconv.Atoi(countryID)
	if err != nil {
		return nil, errors.New("invalid country id")
	}

	states, err := database.Queries.ListStatesByCountry(ctx, int32(id))
	if err != nil {
		return nil, err
	}

	var result []*db.State
	for _, s := range states {
		state := s
		result = append(result, &state)
	}

	return result, nil
}

// CountryID is the resolver for the countryId field.
func (r *stateResolver) CountryID(ctx context.Context, obj *db.State) (string, error) {
	return fmt.Sprintf("%d", obj.CountryID), nil
}
