package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/graphql/models"
	"graphql/internal/db"
	"strconv"
)

// CreateTour is the resolver for the createTour field.
func (r *mutationResolver) CreateTour(ctx context.Context, title string, description *string, categoryID string, cityID string, durationDays int, createdBy string, status string, images []*models.TourImageInput) (*db.Tour, error) {
	if title == "" || categoryID == "" || cityID == "" || createdBy == "" || status == "" {
		return nil, errors.New("title, category_id, city_id, created_by and status are required")
	}

	catID, err := strconv.Atoi(categoryID)
	if err != nil {
		return nil, errors.New("invalid category id")
	}
	city, err := strconv.Atoi(cityID)
	if err != nil {
		return nil, errors.New("invalid city id")
	}
	creatorID, err := strconv.Atoi(createdBy)
	if err != nil {
		return nil, errors.New("invalid created_by id")
	}

	var desc sql.NullString
	if description != nil {
		desc = sql.NullString{String: *description, Valid: true}
	}

	// 1) Tour create
	tour, err := database.Queries.CreateTour(ctx, db.CreateTourParams{
		Title:        title,
		Description:  desc,
		CategoryID:   int32(catID),
		CityID:       int32(city),
		DurationDays: int32(durationDays),
		CreatedBy:    int32(creatorID),
		Status:       status,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images insert
	for _, img := range images {
		if img == nil || img.FileURL == "" {
			continue
		}

		var alt sql.NullString
		if img.AltText != nil {
			alt = sql.NullString{String: *img.AltText, Valid: true}
		}

		_, err := database.Queries.CreateTourImage(ctx, db.CreateTourImageParams{
			TourID:  tour.ID,
			FileUrl: img.FileURL,
			AltText: alt,
		})
		if err != nil {
			return nil, err
		}
	}

	return &tour, nil
}

// UpdateTour is the resolver for the updateTour field.
func (r *mutationResolver) UpdateTour(ctx context.Context, id string, title *string, description *string, categoryID *string, cityID *string, durationDays *int, createdBy *string, status *string, images []*models.TourImageInput) (*db.Tour, error) {
	tourID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	existing, err := database.Queries.GetTour(ctx, int32(tourID))
	if err == sql.ErrNoRows {
		return nil, errors.New("tour not found")
	}
	if err != nil {
		return nil, err
	}

	newTitle := existing.Title
	if title != nil {
		newTitle = *title
	}

	newDesc := existing.Description
	if description != nil {
		newDesc = sql.NullString{String: *description, Valid: true}
	}

	newCategoryID := existing.CategoryID
	if categoryID != nil {
		cid, err := strconv.Atoi(*categoryID)
		if err != nil {
			return nil, errors.New("invalid category id")
		}
		newCategoryID = int32(cid)
	}

	newCityID := existing.CityID
	if cityID != nil {
		cid, err := strconv.Atoi(*cityID)
		if err != nil {
			return nil, errors.New("invalid city id")
		}
		newCityID = int32(cid)
	}

	newDuration := existing.DurationDays
	if durationDays != nil {
		newDuration = int32(*durationDays)
	}

	newCreatedBy := existing.CreatedBy
	if createdBy != nil {
		cb, err := strconv.Atoi(*createdBy)
		if err != nil {
			return nil, errors.New("invalid created_by id")
		}
		newCreatedBy = int32(cb)
	}

	newStatus := existing.Status
	if status != nil {
		newStatus = *status
	}

	// 1) Tour update
	tour, err := database.Queries.UpdateTour(ctx, db.UpdateTourParams{
		ID:           int32(tourID),
		Title:        newTitle,
		Description:  newDesc,
		CategoryID:   newCategoryID,
		CityID:       newCityID,
		DurationDays: newDuration,
		CreatedBy:    newCreatedBy,
		Status:       newStatus,
	})
	if err != nil {
		return nil, err
	}

	// 2) Images argument diya ho to replace karo
	if images != nil {
		// Purane saare images delete
		if err := database.Queries.DeleteTourImagesByTour(ctx, tour.ID); err != nil {
			return nil, err
		}

		// Naye insert
		for _, img := range images {
			if img == nil || img.FileURL == "" {
				continue
			}

			var alt sql.NullString
			if img.AltText != nil {
				alt = sql.NullString{String: *img.AltText, Valid: true}
			}

			_, err := database.Queries.CreateTourImage(ctx, db.CreateTourImageParams{
				TourID:  tour.ID,
				FileUrl: img.FileURL,
				AltText: alt,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	return &tour, nil
}

// DeleteTour is the resolver for the deleteTour field.
func (r *mutationResolver) DeleteTour(ctx context.Context, id string) (*db.Tour, error) {
	tourID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	tour, err := database.Queries.DeleteTour(ctx, int32(tourID))
	if err == sql.ErrNoRows {
		return nil, errors.New("tour not found")
	}
	if err != nil {
		return nil, err
	}

	return &tour, nil
}

// Tour is the resolver for the tour field.
func (r *queryResolver) Tour(ctx context.Context, id string) (*db.Tour, error) {
	tourID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid tour id")
	}

	tour, err := database.Queries.GetTour(ctx, int32(tourID))
	if err == sql.ErrNoRows {
		return nil, errors.New("tour not found")
	}
	if err != nil {
		return nil, err
	}

	return &tour, nil
}

// Tours is the resolver for the tours field.
func (r *queryResolver) Tours(ctx context.Context) ([]*db.Tour, error) {
	toursDB, err := database.Queries.ListTours(ctx)
	if err != nil {
		return nil, err
	}

	tours := make([]*db.Tour, 0, len(toursDB))
	for i := range toursDB {
		t := toursDB[i]
		tours = append(tours, &t)
	}
	return tours, nil
}

// TourImage is the resolver for the tourImage field.
func (r *queryResolver) TourImage(ctx context.Context, id string) (*db.TourImage, error) {
	imgID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid image id")
	}

	img, err := database.Queries.GetTourImageByID(ctx, int32(imgID))
	if err == sql.ErrNoRows {
		return nil, errors.New("image not found")
	}
	if err != nil {
		return nil, err
	}

	return &img, nil
}

// ID is the resolver for the id field.
func (r *tourResolver) ID(ctx context.Context, obj *db.Tour) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Description is the resolver for the description field.
func (r *tourResolver) Description(ctx context.Context, obj *db.Tour) (*string, error) {
	if !obj.Description.Valid {
		return nil, nil
	}
	desc := obj.Description.String
	return &desc, nil
}

// CategoryID is the resolver for the category_id field.
func (r *tourResolver) CategoryID(ctx context.Context, obj *db.Tour) (string, error) {
	return fmt.Sprintf("%d", obj.CategoryID), nil
}

// CityID is the resolver for the city_id field.
func (r *tourResolver) CityID(ctx context.Context, obj *db.Tour) (string, error) {
	return fmt.Sprintf("%d", obj.CityID), nil
}

// CreatedBy is the resolver for the created_by field.
func (r *tourResolver) CreatedBy(ctx context.Context, obj *db.Tour) (string, error) {
	return fmt.Sprintf("%d", obj.CreatedBy), nil
}

// Images is the resolver for the images field.
func (r *tourResolver) Images(ctx context.Context, obj *db.Tour) ([]*db.TourImage, error) {
	imgs, err := database.Queries.ListTourImagesByTour(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	// sqlc likely returns []db.TourImage, gqlgen ko []*db.TourImage chahiye
	out := make([]*db.TourImage, 0, len(imgs))
	for i := range imgs {
		img := imgs[i]
		out = append(out, &img)
	}
	return out, nil
}

// ID is the resolver for the id field.
func (r *tourImageResolver) ID(ctx context.Context, obj *db.TourImage) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// TourID is the resolver for the tour_id field.
func (r *tourImageResolver) TourID(ctx context.Context, obj *db.TourImage) (string, error) {
	return fmt.Sprintf("%d", obj.TourID), nil
}

// AltText is the resolver for the alt_text field.
func (r *tourImageResolver) AltText(ctx context.Context, obj *db.TourImage) (*string, error) {
	if !obj.AltText.Valid {
		return nil, nil
	}
	v := obj.AltText.String
	return &v, nil
}

// Tour returns generated.TourResolver implementation.
func (r *Resolver) Tour() generated.TourResolver { return &tourResolver{r} }

// TourImage returns generated.TourImageResolver implementation.
func (r *Resolver) TourImage() generated.TourImageResolver { return &tourImageResolver{r} }

type tourResolver struct{ *Resolver }
type tourImageResolver struct{ *Resolver }
