type Tour {
  id: UUID!
  title: String!
  description: String
  category_id: UUID!
  city_id: UUID!
  duration_days: Int!
  created_by: UUID!
  status: String!
  created_at: Time!
  updated_at: Time!
  images: [TourImage!]!

  category: Category
  city: City
}

type TourImage {
  id: UUID!
  tour_id: UUID!
  file_url: String!
  alt_text: String
  created_at: Time!
  updated_at: Time!
}

input TourImageInput {
  file_url: String!
  alt_text: String
}

extend type Query {
  tour(id: UUID!): Tour
  tours: [Tour!]!
  tourImage(id: UUID!): TourImage!
}

extend type Mutation {
  createTour(
    title: String!
    description: String
    category_id: UUID!
    city_id: UUID!
    duration_days: Int!
    created_by: UUID!
    status: String!
    images: [TourImageInput!]
  ): Tour!

  updateTour(
    id: UUID!
    title: String
    description: String
    category_id: UUID
    city_id: UUID
    duration_days: Int
    created_by: UUID
    status: String
    images: [TourImageInput!]
  ): Tour!

  deleteTour(id: UUID!): Tour!
}
