package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"database/sql"
	stdErrors "errors"
	"fmt"
	"graphql/database"
	"graphql/graphql/generated"
	"graphql/internal/auth"
	"graphql/internal/db"
	dbtime "graphql/internal/dbTime"
	appErr "graphql/internal/errors"
	"graphql/internal/validation"

	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, fullName string, email string, password string, phone *string) (*db.User, error) {
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}

	if err := validation.ValidateCreateUserInput(validation.CreateUserInput{
		FullName: fullName,
		Email:    email,
		Password: password,
		Phone:    phone,
	}); err != nil {
		return nil, err
	}

	var phoneVal sql.NullString
	if phone != nil {
		phoneVal = sql.NullString{String: *phone, Valid: true}
	}

	// Hash the password before storing
	hashed, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	userDB, err := database.Queries.CreateUser(ctx, db.CreateUserParams{
		FullName: fullName,
		Email:    email,
		Password: string(hashed),
		Phone:    phoneVal,
	})
	if err != nil {
		return nil, appErr.FromDB(err)
	}

	// Convert CreateUserRow to db.User
	user := &db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		RoleID:    userDB.RoleID,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, fullName *string, email *string, password *string, phone *string) (*db.User, error) {
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// Fetch existing user
	existing, err := database.Queries.GetUser(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	// Build update values with defaults from existing
	updateFullName := existing.FullName
	updateEmail := existing.Email
	updatePhone := existing.Phone

	// Apply optional updates
	if fullName != nil {
		updateFullName = *fullName
	}
	if email != nil {
		updateEmail = *email
	}
	if phone != nil {
		updatePhone = sql.NullString{String: *phone, Valid: true}
	}

	// Handle password separately - only update if provided
	updatePassword := "" // empty string = no change (your SQL should handle this)
	if password != nil {
		hashed, err := bcrypt.GenerateFromPassword([]byte(*password), bcrypt.DefaultCost)
		if err != nil {
			return nil, err
		}
		updatePassword = string(hashed)
	}

	// Update via sqlc
	userDB, err := database.Queries.UpdateUser(ctx, db.UpdateUserParams{
		ID:       id,
		FullName: updateFullName,
		Email:    updateEmail,
		Column3:  updatePassword, // empty = no change
		Phone:    updatePhone,
		RoleID:   existing.RoleID,
	})
	if err != nil {
		return nil, appErr.FromDB(err)
	}
	// Convert to db.User and return
	user := &db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		RoleID:    userDB.RoleID,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (*db.User, error) {
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	// Call sqlc delete
	userDB, err := database.Queries.DeleteUser(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}
	// Convert DeleteUserRow → db.User
	user := &db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	return user, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*db.User, error) {
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	userDB, err := database.Queries.GetUser(ctx, id)
	if err != nil {
		if stdErrors.Is(err, sql.ErrNoRows) {
			return nil, appErr.NotFound()
		}
		return nil, appErr.Internal(err)
	}

	// Convert GetUserRow to db.User
	user := &db.User{
		ID:        userDB.ID,
		FullName:  userDB.FullName,
		Email:     userDB.Email,
		Phone:     userDB.Phone,
		RoleID:    userDB.RoleID,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*db.User, error) {
	if err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, dbtime.DataBaseTimeOut)
	defer cancel()
	usersDB, err := database.Queries.ListUsers(ctx)
	if err != nil {
		return nil, fmt.Errorf("list users failed: %w", err)
	}

	users := make([]*db.User, 0, len(usersDB))

	for _, u := range usersDB {
		user := &db.User{
			ID:        u.ID,
			FullName:  u.FullName,
			Email:     u.Email,
			Phone:     u.Phone,
			RoleID:    u.RoleID,
			CreatedAt: u.CreatedAt,
			UpdatedAt: u.UpdatedAt,
		}
		users = append(users, user)
	}

	return users, nil
}

// Phone is the resolver for the phone field.
func (r *userResolver) Phone(ctx context.Context, obj *db.User) (*string, error) {
	if !obj.Phone.Valid {
		return nil, nil
	}
	phone := obj.Phone.String
	return &phone, nil
}

// RoleID is the resolver for the roleId field.
func (r *userResolver) RoleID(ctx context.Context, obj *db.User) (*uuid.UUID, error) {
	if !obj.RoleID.Valid {
		return nil, nil
	}
	roleID := obj.RoleID.UUID
	return &roleID, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
