// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"graphql/models"
)

type LoginResponse struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type Mutation struct {
}

type Query struct {
}
