// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"graphql/internal/db"
)

type LoginResponse struct {
	Token string   `json:"token"`
	User  *db.User `json:"user"`
}

type Mutation struct {
}

type Query struct {
}
