// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  user_id,
  package_id,
  total_price,
  status,
  travel_start_date,
  travel_end_date
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date, created_at, updated_at
`

type CreateBookingParams struct {
	UserID          uuid.UUID `json:"user_id"`
	PackageID       uuid.UUID `json:"package_id"`
	TotalPrice      string    `json:"total_price"`
	Status          string    `json:"status"`
	TravelStartDate time.Time `json:"travel_start_date"`
	TravelEndDate   time.Time `json:"travel_end_date"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.UserID,
		arg.PackageID,
		arg.TotalPrice,
		arg.Status,
		arg.TravelStartDate,
		arg.TravelEndDate,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :one
DELETE FROM bookings
WHERE id = $1
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date, created_at, updated_at
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, deleteBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date, created_at, updated_at
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date, created_at, updated_at
FROM bookings
ORDER BY id
`

func (q *Queries) ListBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PackageID,
			&i.TotalPrice,
			&i.Status,
			&i.BookingDate,
			&i.TravelStartDate,
			&i.TravelEndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsWithUserPackage = `-- name: ListBookingsWithUserPackage :many
SELECT
  b.id,
  b.user_id,
  b.package_id,
  b.total_price,
  b.status,
  b.booking_date,
  b.travel_start_date,
  b.travel_end_date,
  b.created_at,
  b.updated_at,

  u.id         AS user_id_join,
  u.full_name  AS user_name,
  u.email      AS user_email,

  p.id         AS package_id_join,
  p.package_name,
  p.price      AS package_price
FROM bookings b
LEFT JOIN users    u ON u.id = b.user_id
LEFT JOIN packages p ON p.id = b.package_id
ORDER BY b.created_at DESC
`

type ListBookingsWithUserPackageRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	PackageID       uuid.UUID      `json:"package_id"`
	TotalPrice      string         `json:"total_price"`
	Status          string         `json:"status"`
	BookingDate     time.Time      `json:"booking_date"`
	TravelStartDate time.Time      `json:"travel_start_date"`
	TravelEndDate   time.Time      `json:"travel_end_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	UserIDJoin      uuid.NullUUID  `json:"user_id_join"`
	UserName        sql.NullString `json:"user_name"`
	UserEmail       sql.NullString `json:"user_email"`
	PackageIDJoin   uuid.NullUUID  `json:"package_id_join"`
	PackageName     sql.NullString `json:"package_name"`
	PackagePrice    sql.NullString `json:"package_price"`
}

func (q *Queries) ListBookingsWithUserPackage(ctx context.Context) ([]ListBookingsWithUserPackageRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsWithUserPackage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsWithUserPackageRow{}
	for rows.Next() {
		var i ListBookingsWithUserPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PackageID,
			&i.TotalPrice,
			&i.Status,
			&i.BookingDate,
			&i.TravelStartDate,
			&i.TravelEndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserIDJoin,
			&i.UserName,
			&i.UserEmail,
			&i.PackageIDJoin,
			&i.PackageName,
			&i.PackagePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET
  user_id           = COALESCE($1, user_id),
  package_id        = COALESCE($2, package_id),
  total_price       = COALESCE($3, total_price),
  status            = COALESCE($4, status),
  travel_start_date = COALESCE($5, travel_start_date),
  travel_end_date   = COALESCE($6, travel_end_date)
WHERE id = $7
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date, created_at, updated_at
`

type UpdateBookingParams struct {
	UserID          uuid.UUID `json:"user_id"`
	PackageID       uuid.UUID `json:"package_id"`
	TotalPrice      string    `json:"total_price"`
	Status          string    `json:"status"`
	TravelStartDate time.Time `json:"travel_start_date"`
	TravelEndDate   time.Time `json:"travel_end_date"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.UserID,
		arg.PackageID,
		arg.TotalPrice,
		arg.Status,
		arg.TravelStartDate,
		arg.TravelEndDate,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
