// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking_queries.sql

package db

import (
	"context"
	"time"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  user_id,
  package_id,
  total_price,
  status,
  booking_date,
  travel_start_date,
  travel_end_date
) VALUES (
  $1, $2, $3, $4, COALESCE($5, NOW()), $6, $7
)
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date
`

type CreateBookingParams struct {
	UserID          int32       `json:"user_id"`
	PackageID       int32       `json:"package_id"`
	TotalPrice      string      `json:"total_price"`
	Status          string      `json:"status"`
	Column5         interface{} `json:"column_5"`
	TravelStartDate time.Time   `json:"travel_start_date"`
	TravelEndDate   time.Time   `json:"travel_end_date"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.UserID,
		arg.PackageID,
		arg.TotalPrice,
		arg.Status,
		arg.Column5,
		arg.TravelStartDate,
		arg.TravelEndDate,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :one
DELETE FROM bookings
WHERE id = $1
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date
`

func (q *Queries) DeleteBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, deleteBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date
FROM bookings
ORDER BY id
`

func (q *Queries) ListBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PackageID,
			&i.TotalPrice,
			&i.Status,
			&i.BookingDate,
			&i.TravelStartDate,
			&i.TravelEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET
  user_id           = COALESCE($1, user_id),
  package_id        = COALESCE($2, package_id),
  total_price       = COALESCE($3, total_price),
  status            = COALESCE($4, status),
  booking_date      = COALESCE($5, booking_date),
  travel_start_date = COALESCE($6, travel_start_date),
  travel_end_date   = COALESCE($7, travel_end_date)
WHERE id = $8
RETURNING
  id, user_id, package_id, total_price, status,
  booking_date, travel_start_date, travel_end_date
`

type UpdateBookingParams struct {
	UserID          int32     `json:"user_id"`
	PackageID       int32     `json:"package_id"`
	TotalPrice      string    `json:"total_price"`
	Status          string    `json:"status"`
	BookingDate     time.Time `json:"booking_date"`
	TravelStartDate time.Time `json:"travel_start_date"`
	TravelEndDate   time.Time `json:"travel_end_date"`
	ID              int32     `json:"id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.UserID,
		arg.PackageID,
		arg.TotalPrice,
		arg.Status,
		arg.BookingDate,
		arg.TravelStartDate,
		arg.TravelEndDate,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.TotalPrice,
		&i.Status,
		&i.BookingDate,
		&i.TravelStartDate,
		&i.TravelEndDate,
	)
	return i, err
}
