// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_image_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategoryImage = `-- name: CreateCategoryImage :one
INSERT INTO category_images (category_id, file_url, alt_text)
VALUES ($1, $2, $3)
RETURNING id, category_id, file_url, alt_text, created_at, updated_at
`

type CreateCategoryImageParams struct {
	CategoryID uuid.UUID      `json:"category_id"`
	FileUrl    string         `json:"file_url"`
	AltText    sql.NullString `json:"alt_text"`
}

func (q *Queries) CreateCategoryImage(ctx context.Context, arg CreateCategoryImageParams) (CategoryImage, error) {
	row := q.db.QueryRowContext(ctx, createCategoryImage, arg.CategoryID, arg.FileUrl, arg.AltText)
	var i CategoryImage
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryImagesByCategory = `-- name: DeleteCategoryImagesByCategory :exec
DELETE FROM category_images WHERE category_id = $1
`

func (q *Queries) DeleteCategoryImagesByCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryImagesByCategory, categoryID)
	return err
}

const getCategoryImageByID = `-- name: GetCategoryImageByID :one
SELECT id, category_id, file_url, alt_text, created_at, updated_at FROM category_images WHERE id = $1
`

func (q *Queries) GetCategoryImageByID(ctx context.Context, id uuid.UUID) (CategoryImage, error) {
	row := q.db.QueryRowContext(ctx, getCategoryImageByID, id)
	var i CategoryImage
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryImagesByCategory = `-- name: ListCategoryImagesByCategory :many
SELECT id, category_id, file_url, alt_text, created_at, updated_at FROM category_images 
WHERE category_id = $1 
ORDER BY id ASC
`

func (q *Queries) ListCategoryImagesByCategory(ctx context.Context, categoryID uuid.UUID) ([]CategoryImage, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryImagesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryImage{}
	for rows.Next() {
		var i CategoryImage
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.FileUrl,
			&i.AltText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryImage = `-- name: UpdateCategoryImage :one
UPDATE category_images 
SET file_url = $2, alt_text = $3 
WHERE id = $1 
RETURNING id, category_id, file_url, alt_text, created_at, updated_at
`

type UpdateCategoryImageParams struct {
	ID      uuid.UUID      `json:"id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) UpdateCategoryImage(ctx context.Context, arg UpdateCategoryImageParams) (CategoryImage, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryImage, arg.ID, arg.FileUrl, arg.AltText)
	var i CategoryImage
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
