// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (category_name, description)
VALUES ($1, $2)
RETURNING id, category_name, description, created_at, updated_at
`

type CreateCategoryParams struct {
	CategoryName string         `json:"category_name"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.CategoryName, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id, category_name, description, created_at, updated_at
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, deleteCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, category_name, description, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, category_name, description, created_at, updated_at
FROM categories
WHERE category_name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, categoryName string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, categoryName)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, category_name, description, created_at, updated_at
FROM categories
ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
  category_name = COALESCE($2, category_name),
  description = COALESCE($3, description)
WHERE id = $1
RETURNING id, category_name, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID           uuid.UUID      `json:"id"`
	CategoryName string         `json:"category_name"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.CategoryName, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
