// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const cityExists = `-- name: CityExists :one
SELECT EXISTS (
	SELECT 1 FROM cities WHERE id = $1
)
`

func (q *Queries) CityExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, cityExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCity = `-- name: CreateCity :one

INSERT INTO cities (state_id, name)
VALUES ($1, $2)
RETURNING id, state_id, name
`

type CreateCityParams struct {
	StateID uuid.UUID `json:"state_id"`
	Name    string    `json:"name"`
}

// ---------------------- CRUD QUERIES ----------------------
func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, arg.StateID, arg.Name)
	var i City
	err := row.Scan(&i.ID, &i.StateID, &i.Name)
	return i, err
}

const deleteCity = `-- name: DeleteCity :one
DELETE FROM cities
WHERE id = $1
RETURNING id, state_id, name
`

func (q *Queries) DeleteCity(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRowContext(ctx, deleteCity, id)
	var i City
	err := row.Scan(&i.ID, &i.StateID, &i.Name)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT id, state_id, name
FROM cities
WHERE id = $1
`

func (q *Queries) GetCity(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRowContext(ctx, getCity, id)
	var i City
	err := row.Scan(&i.ID, &i.StateID, &i.Name)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT id, state_id, name
FROM cities
ORDER BY id
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.QueryContext(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.ID, &i.StateID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitiesByState = `-- name: ListCitiesByState :many
SELECT id, state_id, name
FROM cities
WHERE state_id = $1
ORDER BY id
`

func (q *Queries) ListCitiesByState(ctx context.Context, stateID uuid.UUID) ([]City, error) {
	rows, err := q.db.QueryContext(ctx, listCitiesByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.ID, &i.StateID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET
  state_id = COALESCE($1, state_id),
  name = COALESCE($2, name)
WHERE id = $3
RETURNING id, state_id, name
`

type UpdateCityParams struct {
	StateID uuid.UUID `json:"state_id"`
	Name    string    `json:"name"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, updateCity, arg.StateID, arg.Name, arg.ID)
	var i City
	err := row.Scan(&i.ID, &i.StateID, &i.Name)
	return i, err
}
