// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country_queries.sql

package db

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateCountry(ctx context.Context, name string) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, name)
	var i Country
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :one
DELETE FROM countries
WHERE id = $1
RETURNING id, name
`

func (q *Queries) DeleteCountry(ctx context.Context, id int32) (Country, error) {
	row := q.db.QueryRowContext(ctx, deleteCountry, id)
	var i Country
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCountry = `-- name: GetCountry :one
SELECT id, name
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountry(ctx context.Context, id int32) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountry, id)
	var i Country
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCountryByName = `-- name: GetCountryByName :one
SELECT id, name
FROM countries
WHERE name = $1
`

func (q *Queries) GetCountryByName(ctx context.Context, name string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByName, name)
	var i Country
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name
FROM countries
ORDER BY id
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET name = COALESCE($1, name)
WHERE id = $2
RETURNING id, name
`

type UpdateCountryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, updateCountry, arg.Name, arg.ID)
	var i Country
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
