// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID              int32     `json:"id"`
	UserID          int32     `json:"user_id"`
	PackageID       int32     `json:"package_id"`
	TotalPrice      string    `json:"total_price"`
	Status          string    `json:"status"`
	BookingDate     time.Time `json:"booking_date"`
	TravelStartDate time.Time `json:"travel_start_date"`
	TravelEndDate   time.Time `json:"travel_end_date"`
}

type Category struct {
	ID           int32          `json:"id"`
	CategoryName string         `json:"category_name"`
	Description  sql.NullString `json:"description"`
}

type City struct {
	ID      int32  `json:"id"`
	StateID int32  `json:"state_id"`
	Name    string `json:"name"`
}

type Country struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Package struct {
	ID          int32          `json:"id"`
	TourID      int32          `json:"tour_id"`
	PackageName string         `json:"package_name"`
	Price       string         `json:"price"`
	Currency    string         `json:"currency"`
	Occupancy   sql.NullString `json:"occupancy"`
	IsFeatured  bool           `json:"is_featured"`
}

type Role struct {
	ID        int32     `json:"id"`
	RoleName  string    `json:"role_name"`
	CreatedAt time.Time `json:"created_at"`
}

type State struct {
	ID        int32  `json:"id"`
	CountryID int32  `json:"country_id"`
	Name      string `json:"name"`
}

type Tour struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   int32          `json:"category_id"`
	CityID       int32          `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	CreatedBy    int32          `json:"created_by"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type TourImage struct {
	ID      int32          `json:"id"`
	TourID  int32          `json:"tour_id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

type User struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     sql.NullString `json:"phone"`
	RoleID    sql.NullInt32  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
