// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package_image_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPackageImage = `-- name: CreatePackageImage :one
INSERT INTO package_images (package_id, file_url, alt_text)
VALUES ($1, $2, $3)
RETURNING id, package_id, file_url, alt_text, created_at, updated_at
`

type CreatePackageImageParams struct {
	PackageID uuid.UUID      `json:"package_id"`
	FileUrl   string         `json:"file_url"`
	AltText   sql.NullString `json:"alt_text"`
}

func (q *Queries) CreatePackageImage(ctx context.Context, arg CreatePackageImageParams) (PackageImage, error) {
	row := q.db.QueryRowContext(ctx, createPackageImage, arg.PackageID, arg.FileUrl, arg.AltText)
	var i PackageImage
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackageImagesByPackage = `-- name: DeletePackageImagesByPackage :exec
DELETE FROM package_images WHERE package_id = $1
`

func (q *Queries) DeletePackageImagesByPackage(ctx context.Context, packageID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePackageImagesByPackage, packageID)
	return err
}

const getPackageImageByID = `-- name: GetPackageImageByID :one
SELECT id, package_id, file_url, alt_text, created_at, updated_at FROM package_images WHERE id = $1
`

func (q *Queries) GetPackageImageByID(ctx context.Context, id uuid.UUID) (PackageImage, error) {
	row := q.db.QueryRowContext(ctx, getPackageImageByID, id)
	var i PackageImage
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackageImagesByPackage = `-- name: ListPackageImagesByPackage :many
SELECT id, package_id, file_url, alt_text, created_at, updated_at FROM package_images 
WHERE package_id = $1 
ORDER BY id ASC
`

func (q *Queries) ListPackageImagesByPackage(ctx context.Context, packageID uuid.UUID) ([]PackageImage, error) {
	rows, err := q.db.QueryContext(ctx, listPackageImagesByPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageImage{}
	for rows.Next() {
		var i PackageImage
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.FileUrl,
			&i.AltText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageImage = `-- name: UpdatePackageImage :one
UPDATE package_images 
SET file_url = $2, alt_text = $3 
WHERE id = $1 
RETURNING id, package_id, file_url, alt_text, created_at, updated_at
`

type UpdatePackageImageParams struct {
	ID      uuid.UUID      `json:"id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) UpdatePackageImage(ctx context.Context, arg UpdatePackageImageParams) (PackageImage, error) {
	row := q.db.QueryRowContext(ctx, updatePackageImage, arg.ID, arg.FileUrl, arg.AltText)
	var i PackageImage
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
