// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (tour_id, package_name, price, currency, occupancy, is_featured)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
`

type CreatePackageParams struct {
	TourID      uuid.UUID      `json:"tour_id"`
	PackageName string         `json:"package_name"`
	Price       string         `json:"price"`
	Currency    sql.NullString `json:"currency"`
	Occupancy   sql.NullString `json:"occupancy"`
	IsFeatured  bool           `json:"is_featured"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.TourID,
		arg.PackageName,
		arg.Price,
		arg.Currency,
		arg.Occupancy,
		arg.IsFeatured,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PackageName,
		&i.Price,
		&i.Currency,
		&i.Occupancy,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :one
DELETE FROM packages
WHERE id = $1
RETURNING id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
`

func (q *Queries) DeletePackage(ctx context.Context, id uuid.UUID) (Package, error) {
	row := q.db.QueryRowContext(ctx, deletePackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PackageName,
		&i.Price,
		&i.Currency,
		&i.Occupancy,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackage = `-- name: GetPackage :one
SELECT id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
FROM packages
WHERE id = $1
`

func (q *Queries) GetPackage(ctx context.Context, id uuid.UUID) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PackageName,
		&i.Price,
		&i.Currency,
		&i.Occupancy,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackages = `-- name: ListPackages :many
SELECT id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
FROM packages
ORDER BY id
`

func (q *Queries) ListPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PackageName,
			&i.Price,
			&i.Currency,
			&i.Occupancy,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByTour = `-- name: ListPackagesByTour :many
SELECT id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
FROM packages
WHERE tour_id = $1
ORDER BY id
`

func (q *Queries) ListPackagesByTour(ctx context.Context, tourID uuid.UUID) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PackageName,
			&i.Price,
			&i.Currency,
			&i.Occupancy,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
SET
  tour_id      = COALESCE($1, tour_id),
  package_name = COALESCE($2, package_name),
  price        = COALESCE($3, price),
  currency     = COALESCE($4, currency),
  occupancy    = COALESCE($5, occupancy),
  is_featured  = COALESCE($6, is_featured)
WHERE id = $7
RETURNING id, tour_id, package_name, price, currency, occupancy, is_featured, created_at, updated_at
`

type UpdatePackageParams struct {
	TourID      uuid.UUID      `json:"tour_id"`
	PackageName string         `json:"package_name"`
	Price       string         `json:"price"`
	Currency    sql.NullString `json:"currency"`
	Occupancy   sql.NullString `json:"occupancy"`
	IsFeatured  bool           `json:"is_featured"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, updatePackage,
		arg.TourID,
		arg.PackageName,
		arg.Price,
		arg.Currency,
		arg.Occupancy,
		arg.IsFeatured,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PackageName,
		&i.Price,
		&i.Currency,
		&i.Occupancy,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
