// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: point_of_interest_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPOI = `-- name: CreatePOI :one
INSERT INTO points_of_interest (name, description, city_id, type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, city_id, type, created_at, updated_at
`

type CreatePOIParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CityID      uuid.UUID      `json:"city_id"`
	Type        string         `json:"type"`
}

func (q *Queries) CreatePOI(ctx context.Context, arg CreatePOIParams) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, createPOI,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Type,
	)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePOI = `-- name: DeletePOI :one
DELETE FROM points_of_interest
WHERE id = $1
RETURNING id, name, description, city_id, type, created_at, updated_at
`

func (q *Queries) DeletePOI(ctx context.Context, id uuid.UUID) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, deletePOI, id)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPOI = `-- name: GetPOI :one
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
WHERE id = $1
`

func (q *Queries) GetPOI(ctx context.Context, id uuid.UUID) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, getPOI, id)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPOIs = `-- name: ListPOIs :many
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
ORDER BY id ASC
`

func (q *Queries) ListPOIs(ctx context.Context) ([]PointsOfInterest, error) {
	rows, err := q.db.QueryContext(ctx, listPOIs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsOfInterest{}
	for rows.Next() {
		var i PointsOfInterest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOIsByCity = `-- name: ListPOIsByCity :many
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
WHERE city_id = $1
ORDER BY id ASC
`

func (q *Queries) ListPOIsByCity(ctx context.Context, cityID uuid.UUID) ([]PointsOfInterest, error) {
	rows, err := q.db.QueryContext(ctx, listPOIsByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsOfInterest{}
	for rows.Next() {
		var i PointsOfInterest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOIsWithCity = `-- name: ListPOIsWithCity :many
SELECT
  poi.id,
  poi.name as poi_name,
  poi.description,
  poi.city_id,
  poi.type,
  poi.created_at,
  poi.updated_at,

  ci.id as city_id_join,
  ci.name as city_name
FROM points_of_interest poi
LEFT JOIN cities ci ON ci.id = poi.city_id
ORDER BY poi.created_at DESC
`

type ListPOIsWithCityRow struct {
	ID          uuid.UUID      `json:"id"`
	PoiName     string         `json:"poi_name"`
	Description sql.NullString `json:"description"`
	CityID      uuid.UUID      `json:"city_id"`
	Type        string         `json:"type"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CityIDJoin  uuid.NullUUID  `json:"city_id_join"`
	CityName    sql.NullString `json:"city_name"`
}

func (q *Queries) ListPOIsWithCity(ctx context.Context) ([]ListPOIsWithCityRow, error) {
	rows, err := q.db.QueryContext(ctx, listPOIsWithCity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPOIsWithCityRow{}
	for rows.Next() {
		var i ListPOIsWithCityRow
		if err := rows.Scan(
			&i.ID,
			&i.PoiName,
			&i.Description,
			&i.CityID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CityIDJoin,
			&i.CityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOI = `-- name: UpdatePOI :one
UPDATE points_of_interest
SET
  name        = COALESCE($2, name),
  description = COALESCE($3, description),
  city_id     = COALESCE($4, city_id),
  type        = COALESCE($5, type)
WHERE id = $1
RETURNING id, name, description, city_id, type, created_at, updated_at
`

type UpdatePOIParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CityID      uuid.UUID      `json:"city_id"`
	Type        string         `json:"type"`
}

func (q *Queries) UpdatePOI(ctx context.Context, arg UpdatePOIParams) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, updatePOI,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Type,
	)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
