// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: point_of_interest_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPOI = `-- name: CreatePOI :one
INSERT INTO points_of_interest (name, description, city_id, type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, city_id, type, created_at, updated_at
`

type CreatePOIParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CityID      uuid.UUID      `json:"city_id"`
	Type        string         `json:"type"`
}

func (q *Queries) CreatePOI(ctx context.Context, arg CreatePOIParams) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, createPOI,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Type,
	)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePOI = `-- name: DeletePOI :one
DELETE FROM points_of_interest
WHERE id = $1
RETURNING id, name, description, city_id, type, created_at, updated_at
`

func (q *Queries) DeletePOI(ctx context.Context, id uuid.UUID) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, deletePOI, id)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPOI = `-- name: GetPOI :one
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
WHERE id = $1
`

func (q *Queries) GetPOI(ctx context.Context, id uuid.UUID) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, getPOI, id)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPOIs = `-- name: ListPOIs :many
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListPOIsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPOIs(ctx context.Context, arg ListPOIsParams) ([]PointsOfInterest, error) {
	rows, err := q.db.QueryContext(ctx, listPOIs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsOfInterest{}
	for rows.Next() {
		var i PointsOfInterest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOIsByCity = `-- name: ListPOIsByCity :many
SELECT id, name, description, city_id, type, created_at, updated_at
FROM points_of_interest
WHERE city_id = $1
ORDER BY id ASC
`

func (q *Queries) ListPOIsByCity(ctx context.Context, cityID uuid.UUID) ([]PointsOfInterest, error) {
	rows, err := q.db.QueryContext(ctx, listPOIsByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsOfInterest{}
	for rows.Next() {
		var i PointsOfInterest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOI = `-- name: UpdatePOI :one
UPDATE points_of_interest
SET
  name        = COALESCE(NULLIF($1, ''), name),
  description = COALESCE($2, description),
  city_id     = COALESCE($3, city_id),
  type        = COALESCE(NULLIF($4, ''), type),
  updated_at  = NOW()
WHERE id = $5
RETURNING
  id,
  name,
  description,
  city_id,
  type,
  created_at,
  updated_at
`

type UpdatePOIParams struct {
	Name        interface{}    `json:"name"`
	Description sql.NullString `json:"description"`
	CityID      uuid.UUID      `json:"city_id"`
	Type        interface{}    `json:"type"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePOI(ctx context.Context, arg UpdatePOIParams) (PointsOfInterest, error) {
	row := q.db.QueryRowContext(ctx, updatePOI,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Type,
		arg.ID,
	)
	var i PointsOfInterest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
