// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: point_of_interest_image_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPOIImage = `-- name: CreatePOIImage :one
INSERT INTO point_of_interest_images (poi_id, file_url, alt_text)
VALUES ($1, $2, $3)
RETURNING id, poi_id, file_url, alt_text, created_at, updated_at
`

type CreatePOIImageParams struct {
	PoiID   uuid.UUID      `json:"poi_id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) CreatePOIImage(ctx context.Context, arg CreatePOIImageParams) (PointOfInterestImage, error) {
	row := q.db.QueryRowContext(ctx, createPOIImage, arg.PoiID, arg.FileUrl, arg.AltText)
	var i PointOfInterestImage
	err := row.Scan(
		&i.ID,
		&i.PoiID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePOIImagesByPOI = `-- name: DeletePOIImagesByPOI :exec
DELETE FROM point_of_interest_images WHERE poi_id = $1
`

func (q *Queries) DeletePOIImagesByPOI(ctx context.Context, poiID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePOIImagesByPOI, poiID)
	return err
}

const getPOIImageByID = `-- name: GetPOIImageByID :one
SELECT id, poi_id, file_url, alt_text, created_at, updated_at FROM point_of_interest_images WHERE id = $1
`

func (q *Queries) GetPOIImageByID(ctx context.Context, id uuid.UUID) (PointOfInterestImage, error) {
	row := q.db.QueryRowContext(ctx, getPOIImageByID, id)
	var i PointOfInterestImage
	err := row.Scan(
		&i.ID,
		&i.PoiID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPOIImagesByPOI = `-- name: ListPOIImagesByPOI :many
SELECT id, poi_id, file_url, alt_text, created_at, updated_at FROM point_of_interest_images 
WHERE poi_id = $1 
ORDER BY id ASC
`

func (q *Queries) ListPOIImagesByPOI(ctx context.Context, poiID uuid.UUID) ([]PointOfInterestImage, error) {
	rows, err := q.db.QueryContext(ctx, listPOIImagesByPOI, poiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointOfInterestImage{}
	for rows.Next() {
		var i PointOfInterestImage
		if err := rows.Scan(
			&i.ID,
			&i.PoiID,
			&i.FileUrl,
			&i.AltText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOIImage = `-- name: UpdatePOIImage :one
UPDATE point_of_interest_images 
SET file_url = $2, alt_text = $3 
WHERE id = $1 
RETURNING id, poi_id, file_url, alt_text, created_at, updated_at
`

type UpdatePOIImageParams struct {
	ID      uuid.UUID      `json:"id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) UpdatePOIImage(ctx context.Context, arg UpdatePOIImageParams) (PointOfInterestImage, error) {
	row := q.db.QueryRowContext(ctx, updatePOIImage, arg.ID, arg.FileUrl, arg.AltText)
	var i PointOfInterestImage
	err := row.Scan(
		&i.ID,
		&i.PoiID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
