// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTour = `-- name: CreateTour :one
INSERT INTO tours (title, description, category_id, city_id, duration_days, created_by, status) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

type CreateTourParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   int32          `json:"category_id"`
	CityID       int32          `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	CreatedBy    int32          `json:"created_by"`
	Status       string         `json:"status"`
}

// tour related queries
func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, createTour,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.CreatedBy,
		arg.Status,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, password, phone, role_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, email, phone, role_id, created_at, updated_at
`

type CreateUserParams struct {
	FullName string         `json:"full_name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Phone    sql.NullString `json:"phone"`
	RoleID   sql.NullInt32  `json:"role_id"`
}

type CreateUserRow struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    sql.NullInt32  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.RoleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTour = `-- name: DeleteTour :one
DELETE FROM tours WHERE id = $1 RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

func (q *Queries) DeleteTour(ctx context.Context, id int32) (Tour, error) {
	row := q.db.QueryRowContext(ctx, deleteTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, full_name, email, phone, created_at, updated_at
`

type DeleteUserRow struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, id int32) (DeleteUserRow, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i DeleteUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTour = `-- name: GetTour :one
SELECT id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at FROM tours WHERE id = $1
`

func (q *Queries) GetTour(ctx context.Context, id int32) (Tour, error) {
	row := q.db.QueryRowContext(ctx, getTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, phone, role_id, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    sql.NullInt32  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password, phone, role_id, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTours = `-- name: ListTours :many
SELECT id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at FROM tours ORDER BY created_at DESC
`

func (q *Queries) ListTours(ctx context.Context) ([]Tour, error) {
	rows, err := q.db.QueryContext(ctx, listTours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tour{}
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.CityID,
			&i.DurationDays,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, phone, role_id, created_at, updated_at
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    sql.NullInt32  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTour = `-- name: UpdateTour :one
UPDATE tours SET title = COALESCE($2, title), description = COALESCE($3, description), category_id = COALESCE($4, category_id), city_id = COALESCE($5, city_id), duration_days = COALESCE($6, duration_days), status = COALESCE($7, status), updated_at = NOW() WHERE id = $1 RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

type UpdateTourParams struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   int32          `json:"category_id"`
	CityID       int32          `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	Status       string         `json:"status"`
}

func (q *Queries) UpdateTour(ctx context.Context, arg UpdateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, updateTour,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.Status,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  full_name = COALESCE($1, full_name),
  email = COALESCE($2, email),
  password = COALESCE($3, password),
  phone = COALESCE($4, phone),
  role_id = COALESCE($5, role_id),
  updated_at = NOW()
WHERE id = $6
RETURNING id, full_name, email, phone, role_id, created_at, updated_at
`

type UpdateUserParams struct {
	FullName sql.NullString `json:"full_name"`
	Email    sql.NullString `json:"email"`
	Password sql.NullString `json:"password"`
	Phone    sql.NullString `json:"phone"`
	RoleID   sql.NullInt32  `json:"role_id"`
	ID       int32          `json:"id"`
}

type UpdateUserRow struct {
	ID        int32          `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    sql.NullInt32  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.RoleID,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
