// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, role_name, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName, &i.CreatedAt)
	return i, err
}
