// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createState = `-- name: CreateState :one
INSERT INTO states (country_id, name)
VALUES ($1, $2)
RETURNING id, country_id, name
`

type CreateStateParams struct {
	CountryID uuid.UUID `json:"country_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, createState, arg.CountryID, arg.Name)
	var i State
	err := row.Scan(&i.ID, &i.CountryID, &i.Name)
	return i, err
}

const deleteState = `-- name: DeleteState :one
DELETE FROM states
WHERE id = $1
RETURNING id, country_id, name
`

func (q *Queries) DeleteState(ctx context.Context, id uuid.UUID) (State, error) {
	row := q.db.QueryRowContext(ctx, deleteState, id)
	var i State
	err := row.Scan(&i.ID, &i.CountryID, &i.Name)
	return i, err
}

const getState = `-- name: GetState :one
SELECT id, country_id, name
FROM states
WHERE id = $1
`

func (q *Queries) GetState(ctx context.Context, id uuid.UUID) (State, error) {
	row := q.db.QueryRowContext(ctx, getState, id)
	var i State
	err := row.Scan(&i.ID, &i.CountryID, &i.Name)
	return i, err
}

const getStateByName = `-- name: GetStateByName :one
SELECT id, country_id, name
FROM states
WHERE name = $1
`

func (q *Queries) GetStateByName(ctx context.Context, name string) (State, error) {
	row := q.db.QueryRowContext(ctx, getStateByName, name)
	var i State
	err := row.Scan(&i.ID, &i.CountryID, &i.Name)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT id, country_id, name
FROM states
ORDER BY id
`

func (q *Queries) ListStates(ctx context.Context) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, listStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(&i.ID, &i.CountryID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesByCountry = `-- name: ListStatesByCountry :many
SELECT id, country_id, name
FROM states
WHERE country_id = $1
ORDER BY id
`

func (q *Queries) ListStatesByCountry(ctx context.Context, countryID uuid.UUID) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, listStatesByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(&i.ID, &i.CountryID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateState = `-- name: UpdateState :one
UPDATE states
SET
  country_id = COALESCE($1, country_id),
  name = COALESCE($2, name)
WHERE id = $3
RETURNING id, country_id, name
`

type UpdateStateParams struct {
	CountryID uuid.UUID `json:"country_id"`
	Name      string    `json:"name"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, updateState, arg.CountryID, arg.Name, arg.ID)
	var i State
	err := row.Scan(&i.ID, &i.CountryID, &i.Name)
	return i, err
}
