// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_image_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTourImage = `-- name: CreateTourImage :one
INSERT INTO tour_images (tour_id, file_url, alt_text)
VALUES ($1, $2, $3)
RETURNING id, tour_id, file_url, alt_text, created_at, updated_at
`

type CreateTourImageParams struct {
	TourID  uuid.UUID      `json:"tour_id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) CreateTourImage(ctx context.Context, arg CreateTourImageParams) (TourImage, error) {
	row := q.db.QueryRowContext(ctx, createTourImage, arg.TourID, arg.FileUrl, arg.AltText)
	var i TourImage
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTourImagesByTour = `-- name: DeleteTourImagesByTour :exec

DELETE FROM tour_images WHERE tour_id = $1
`

// or created_at if you add it
func (q *Queries) DeleteTourImagesByTour(ctx context.Context, tourID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTourImagesByTour, tourID)
	return err
}

const getTourImageByID = `-- name: GetTourImageByID :one
SELECT id, tour_id, file_url, alt_text, created_at, updated_at FROM tour_images WHERE id = $1
`

func (q *Queries) GetTourImageByID(ctx context.Context, id uuid.UUID) (TourImage, error) {
	row := q.db.QueryRowContext(ctx, getTourImageByID, id)
	var i TourImage
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTourImagesByTour = `-- name: ListTourImagesByTour :many
SELECT id, tour_id, file_url, alt_text, created_at, updated_at FROM tour_images 
WHERE tour_id = $1 
ORDER BY id ASC
`

func (q *Queries) ListTourImagesByTour(ctx context.Context, tourID uuid.UUID) ([]TourImage, error) {
	rows, err := q.db.QueryContext(ctx, listTourImagesByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourImage{}
	for rows.Next() {
		var i TourImage
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.FileUrl,
			&i.AltText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTourImage = `-- name: UpdateTourImage :one
UPDATE tour_images 
SET file_url = $2, alt_text = $3 
WHERE id = $1 
RETURNING id, tour_id, file_url, alt_text, created_at, updated_at
`

type UpdateTourImageParams struct {
	ID      uuid.UUID      `json:"id"`
	FileUrl string         `json:"file_url"`
	AltText sql.NullString `json:"alt_text"`
}

func (q *Queries) UpdateTourImage(ctx context.Context, arg UpdateTourImageParams) (TourImage, error) {
	row := q.db.QueryRowContext(ctx, updateTourImage, arg.ID, arg.FileUrl, arg.AltText)
	var i TourImage
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.FileUrl,
		&i.AltText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
