// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTour = `-- name: CreateTour :one
INSERT INTO tours (title, description, category_id, city_id, duration_days, created_by, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

type CreateTourParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CityID       uuid.UUID      `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	CreatedBy    uuid.UUID      `json:"created_by"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, createTour,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.CreatedBy,
		arg.Status,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTour = `-- name: DeleteTour :one
DELETE FROM tours
WHERE id = $1
RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

func (q *Queries) DeleteTour(ctx context.Context, id uuid.UUID) (Tour, error) {
	row := q.db.QueryRowContext(ctx, deleteTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTour = `-- name: GetTour :one
SELECT id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
FROM tours
WHERE id = $1
`

func (q *Queries) GetTour(ctx context.Context, id uuid.UUID) (Tour, error) {
	row := q.db.QueryRowContext(ctx, getTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTours = `-- name: ListTours :many
SELECT id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
FROM tours
ORDER BY id
`

func (q *Queries) ListTours(ctx context.Context) ([]Tour, error) {
	rows, err := q.db.QueryContext(ctx, listTours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tour{}
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.CityID,
			&i.DurationDays,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTour = `-- name: UpdateTour :one
UPDATE tours
SET
  title         = COALESCE($1, title),
  description   = COALESCE($2, description),
  category_id   = COALESCE($3, category_id),
  city_id       = COALESCE($4, city_id),
  duration_days = COALESCE($5, duration_days),
  created_by    = COALESCE($6, created_by),
  status        = COALESCE($7, status),
  updated_at    = NOW()
WHERE id = $8
RETURNING id, title, description, category_id, city_id, duration_days, created_by, status, created_at, updated_at
`

type UpdateTourParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CityID       uuid.UUID      `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	CreatedBy    uuid.UUID      `json:"created_by"`
	Status       string         `json:"status"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTour(ctx context.Context, arg UpdateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, updateTour,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.CreatedBy,
		arg.Status,
		arg.ID,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
