// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTour = `-- name: CreateTour :one
INSERT INTO tours (title, description, category_id, city_id, duration_days, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, category_id, city_id, duration_days, status, created_at, updated_at
`

type CreateTourParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CityID       uuid.UUID      `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, createTour,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.Status,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTour = `-- name: DeleteTour :one
DELETE FROM tours
WHERE id = $1
RETURNING id, title, description, category_id, city_id, duration_days, status, created_at, updated_at
`

func (q *Queries) DeleteTour(ctx context.Context, id uuid.UUID) (Tour, error) {
	row := q.db.QueryRowContext(ctx, deleteTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTour = `-- name: GetTour :one
SELECT id, title, description, category_id, city_id, duration_days, status, created_at, updated_at
FROM tours
WHERE id = $1
`

func (q *Queries) GetTour(ctx context.Context, id uuid.UUID) (Tour, error) {
	row := q.db.QueryRowContext(ctx, getTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTours = `-- name: ListTours :many
SELECT id, title, description, category_id, city_id, duration_days, status, created_at, updated_at
FROM tours
ORDER BY id
`

func (q *Queries) ListTours(ctx context.Context) ([]Tour, error) {
	rows, err := q.db.QueryContext(ctx, listTours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tour{}
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.CityID,
			&i.DurationDays,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToursWithCategoryCity = `-- name: ListToursWithCategoryCity :many
SELECT
  t.id,
  t.title,
  t.description,
  t.category_id,
  t.city_id,
  t.duration_days,
  t.status,
  t.created_at,
  t.updated_at,

  c.id as category_id_join,
  c.category_name as category_name,

  ci.id as city_id_join,
  ci.name as city_name
FROM tours t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN cities ci ON ci.id = t.city_id
ORDER BY t.created_at DESC
`

type ListToursWithCategoryCityRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	CategoryID     uuid.UUID      `json:"category_id"`
	CityID         uuid.UUID      `json:"city_id"`
	DurationDays   int32          `json:"duration_days"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CategoryIDJoin uuid.NullUUID  `json:"category_id_join"`
	CategoryName   sql.NullString `json:"category_name"`
	CityIDJoin     uuid.NullUUID  `json:"city_id_join"`
	CityName       sql.NullString `json:"city_name"`
}

func (q *Queries) ListToursWithCategoryCity(ctx context.Context) ([]ListToursWithCategoryCityRow, error) {
	rows, err := q.db.QueryContext(ctx, listToursWithCategoryCity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToursWithCategoryCityRow{}
	for rows.Next() {
		var i ListToursWithCategoryCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.CityID,
			&i.DurationDays,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryIDJoin,
			&i.CategoryName,
			&i.CityIDJoin,
			&i.CityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTour = `-- name: UpdateTour :one
UPDATE tours
SET
  title         = COALESCE($1, title),
  description   = COALESCE($2, description),
  category_id   = COALESCE($3, category_id),
  city_id       = COALESCE($4, city_id),
  duration_days = COALESCE($5, duration_days),
  status        = COALESCE($6, status),
  updated_at    = NOW()
WHERE id = $7
RETURNING id, title, description, category_id, city_id, duration_days, status, created_at, updated_at
`

type UpdateTourParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CityID       uuid.UUID      `json:"city_id"`
	DurationDays int32          `json:"duration_days"`
	Status       string         `json:"status"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTour(ctx context.Context, arg UpdateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, updateTour,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CityID,
		arg.DurationDays,
		arg.Status,
		arg.ID,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CityID,
		&i.DurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
