// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, password, phone, role_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, email, phone, role_id, created_at, updated_at
`

type CreateUserParams struct {
	FullName string         `json:"full_name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Phone    sql.NullString `json:"phone"`
	RoleID   uuid.NullUUID  `json:"role_id"`
}

type CreateUserRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    uuid.NullUUID  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.RoleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, full_name, email, phone, created_at, updated_at
`

type DeleteUserRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (DeleteUserRow, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i DeleteUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, phone, role_id, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    uuid.NullUUID  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password, phone, role_id, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, phone, role_id, created_at, updated_at
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    uuid.NullUUID  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  full_name = COALESCE($1, full_name),
  email = COALESCE($2, email),
  password = COALESCE($3, password),
  phone = COALESCE($4, phone),
  role_id = COALESCE($5, role_id),
  updated_at = NOW()
WHERE id = $6
RETURNING id, full_name, email, phone, role_id, created_at, updated_at
`

type UpdateUserParams struct {
	FullName string         `json:"full_name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Phone    sql.NullString `json:"phone"`
	RoleID   uuid.NullUUID  `json:"role_id"`
	ID       uuid.UUID      `json:"id"`
}

type UpdateUserRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	RoleID    uuid.NullUUID  `json:"role_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.RoleID,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
